// Flat ESLint config (ESLint 9+). Lints the workspace packages and the gate
// scripts.
//
// Trimmed from the v12 app repo's config: the svelte plugin, the browser
// globals, the `.svelte` parser block and the SvelteKit / Deno / wasm-pack
// exclusions are gone, because this project has no app. Everything else is
// carried over deliberately, including the rule tuning below — those overrides
// are decisions with reasons, not leftovers, so they travel with the code.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/*.cjs',
      // 380 dated, already-run apply-scripts kept as the provenance trail. They
      // are a historical record rather than maintained source, and several were
      // written against a directory layout that no longer exists, so linting
      // them yields noise nobody can act on without rewriting history. A new
      // authoring script is reviewed by hand and gated on its EFFECT, via
      // `registry:lint` over the data it writes.
      'scripts/authoring/**',
      // Generated by scripts/build-compound-chunks.mjs, and gitignored.
      'packages/registry/data/compounds/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: { globals: { ...globals.node } },
    rules: {
      // Allow deliberately-unused identifiers when prefixed with `_`
      // (destructure-rest discards, intentionally-ignored args/catches).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
      // TypeScript already errors on genuinely-undefined identifiers, and
      // `no-undef` false-positives on type-only references and generic params.
      // typescript-eslint's own guidance is to leave it off in TS projects.
      'no-undef': 'off',
    },
  },

  // Gate and ETL scripts are CLIs run through tsx; `any` when shaping untyped
  // external JSON (NCBI, Reactome, Recon3D) is pragmatic and not worth typing
  // out. Stray escapes inside large inline data strings are not worth churn.
  {
    files: ['scripts/**'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-useless-escape': 'off',
    },
  },

  // Test fixtures routinely cast through `any` to poke at internals.
  {
    files: ['**/*.test.ts', '**/*.spec.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
);
