/**
 * Recon3D cross-reference helpers.
 *
 * Recon3D (Brunk et al. 2018, PMID:29457794) is a genome-scale
 * reconstruction of human metabolism: ~13k reactions, ~4k metabolites,
 * ~2k genes, organized into ~111 named subsystems. v8 pathways carry
 * an optional `recon3d_subsystem` string that names the matching
 * subsystem; this module provides lookup over that field.
 *
 * The data file `recon3d-map.json` is the persisted snapshot of the
 * v8 ↔ Recon3D subsystem alignment. It can be regenerated by running
 * `scripts/recon3d/rebuild-map.ts` after editing pathways.json.
 *
 * Stable IDs:
 *   - subsystem name (string)                — Pathway.recon3d_subsystem
 *   - BiGG reaction ID (e.g. "HEX1")         — PathwayStep.recon3d_reaction_ids[]
 *   - BiGG metabolite ID (e.g. "glc__D")     — Compound.recon3d_metabolite_id
 *   - HGNC gene symbol (e.g. "TPH2")         — Compound.recon3d_gene_symbol
 */

import type { Pathway } from '@xeno/core';

export interface Recon3dSubsystem {
  /** Canonical Recon3D subsystem name; matches Brunk 2018 spelling/casing. */
  name: string;
  /** v8 pathway slugs that align with this subsystem (forward index). */
  pathways: string[];
}

export interface Recon3dMap {
  _meta: {
    source: string;
    source_pmid: string;
    source_url: string;
    version: string;
    note: string;
  };
  subsystems: Recon3dSubsystem[];
}

/**
 * Build an in-memory index of subsystem → pathway slugs from the live
 * pathway set. Use this when you need a fresh snapshot off pathways.json
 * (e.g. when running the rebuild script or when the persisted map is
 * known to be stale). Most consumers should read recon3d-map.json
 * directly — it's the auditable, version-controlled source of truth.
 */
export function buildSubsystemIndex(pathways: Pathway[]): Map<string, string[]> {
  const idx = new Map<string, string[]>();
  for (const p of pathways) {
    if (!p.recon3d_subsystem) continue;
    const arr = idx.get(p.recon3d_subsystem) ?? [];
    arr.push(p.slug);
    idx.set(p.recon3d_subsystem, arr);
  }
  for (const arr of idx.values()) arr.sort();
  return idx;
}

/**
 * Find pathways that share a Recon3D subsystem with the given pathway.
 * Returns the OTHER pathway slugs (excludes `excludeSlug` itself). Used
 * by the pathway detail page to show siblings under the badge.
 */
export function findSiblings(
  pathways: Pathway[],
  subsystem: string,
  excludeSlug?: string,
): string[] {
  return pathways
    .filter((p) => p.recon3d_subsystem === subsystem && p.slug !== excludeSlug)
    .map((p) => p.slug)
    .sort();
}

/**
 * Reverse lookup: given a v8 pathway slug, return its Recon3D subsystem
 * name (or null if untagged). Mostly a convenience wrapper since the
 * field is already on Pathway — useful when the consumer only has the
 * slug at hand.
 */
export function subsystemForPathway(pathways: Pathway[], slug: string): string | null {
  const p = pathways.find((x) => x.slug === slug);
  return p?.recon3d_subsystem ?? null;
}

/**
 * vmh.life deep-link for a subsystem name. The URL form is documented at
 * https://www.vmh.life/ and uses the subsystem name as a URL-encoded
 * query parameter. Returns null if the name is empty.
 */
export function vmhSubsystemUrl(name: string): string | null {
  if (!name) return null;
  return `https://www.vmh.life/#subsystem/${encodeURIComponent(name)}`;
}

/**
 * vmh.life deep-link for a BiGG metabolite ID (e.g. "atp", "glc__D").
 * BiGG IDs are case-sensitive and use double-underscore for compartment
 * qualifiers; we pass the bare ID through verbatim.
 */
export function vmhMetaboliteUrl(biggId: string): string | null {
  if (!biggId) return null;
  return `https://www.vmh.life/#metabolite/${encodeURIComponent(biggId)}`;
}

/**
 * vmh.life deep-link for a BiGG reaction ID (e.g. "HEX1", "PGI", "PFK").
 */
export function vmhReactionUrl(biggId: string): string | null {
  if (!biggId) return null;
  return `https://www.vmh.life/#reaction/${encodeURIComponent(biggId)}`;
}
