/**
 * 2026-05-03-wave-0b-prescription-meds.ts — Wave 0b first sub-batch.
 *
 * Catalog stub expansion per ROADMAP.md §0b. Adds the highest-DDI-impact
 * prescription drugs: CYP3A4 / CYP2C9 / CYP2C19 / CYP1A2 perpetrators,
 * cardiovascular workhorses, sulfonylureas + DPP-4i + PDE5i, PPIs, top
 * antibiotics, NSAIDs, antiseizure, triptans, antihistamines, asthma
 * inhalers, antipsychotics. Each stub names key receptors / target tissues
 * in the mechanism prose so the systems tagger picks them up.
 *
 * This is stub authoring — no PK params, no source_pmid for refs. Wave 1a
 * (top-100 prescribed-meds full PK) consumes these stubs and adds the
 * literature-anchored ka/V/F values.
 *
 * Idempotent. Run, then re-run the systems tagger to land system tags.
 *
 * Run:  pnpm tsx scripts/authoring/2026-05-03-wave-0b-prescription-meds.ts
 *       pnpm tsx scripts/authoring/2026-05-02-systems-tagging.ts
 *       pnpm registry:lint && pnpm -r test
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const COMPOUNDS_PATH = join(__dirname, '..', '..', 'packages', 'registry', 'data', 'compounds.json');

type Stub = {
  slug: string;
  name: string;
  aliases: string[];
  category: string;
  mechanism: string;
  routes: string[];
  doses: Record<string, { min: number; max: number; typical: number; unit?: string }>;
  half_life_hr: Record<string, number>;
  mw_g_mol?: number;
  refs: string[];
};

const STUBS: Stub[] = [
  // ── ANTIFUNGALS — major CYP3A4 perpetrators ───────────────────────
  {
    slug: 'fluconazole',
    name: 'Fluconazole',
    aliases: ['Diflucan'],
    category: 'pharmacological',
    mechanism: 'Triazole antifungal — inhibits Candida / Cryptococcus 14α-demethylase (CYP51) blocking ergosterol synthesis. In humans inhibits CYP2C9, CYP2C19, and CYP3A4 — moderate DDI perpetrator at doses ≥ 200 mg/d (warfarin INR rises predictably). Renally cleared; long t½ allows once-daily dosing.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 100, max: 400, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 30 },
    mw_g_mol: 306.27,
    refs: [],
  },
  {
    slug: 'ketoconazole',
    name: 'Ketoconazole (oral)',
    aliases: ['Nizoral'],
    category: 'pharmacological',
    mechanism: 'Imidazole antifungal — inhibits fungal CYP51 ergosterol synthesis. Potent CYP3A4 inhibitor in human liver — historically the gold-standard "strong CYP3A4 perpetrator" for DDI studies. Oral use restricted by FDA 2013 to mycoses unresponsive to alternatives due to hepatotoxicity + adrenal suppression.',
    routes: ['PO', 'TD'],
    doses: { 'PO': { min: 200, max: 400, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 531.43,
    refs: [],
  },
  {
    slug: 'itraconazole',
    name: 'Itraconazole',
    aliases: ['Sporanox'],
    category: 'pharmacological',
    mechanism: 'Triazole antifungal — fungal CYP51 inhibitor. Strong CYP3A4 inhibitor + P-glycoprotein inhibitor — major DDI perpetrator (statin myopathy, ergot crisis, sedative oversedation). Highly lipophilic; absorption requires gastric acid + food (capsule) but solution form is enhanced.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 100, max: 400, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 21 },
    mw_g_mol: 705.63,
    refs: [],
  },
  {
    slug: 'voriconazole',
    name: 'Voriconazole',
    aliases: ['Vfend'],
    category: 'pharmacological',
    mechanism: 'Second-gen triazole; extended-spectrum antifungal (Aspergillus, Fusarium, Scedosporium). Strong CYP2C19 + CYP2C9 + CYP3A4 inhibitor. CYP2C19 polymorphism drives extreme exposure variability — TDM strongly recommended. Visual disturbances (~30%) at therapeutic levels.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 100, max: 300, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 349.31,
    refs: [],
  },
  {
    slug: 'posaconazole',
    name: 'Posaconazole',
    aliases: ['Noxafil'],
    category: 'pharmacological',
    mechanism: 'Broad-spectrum triazole (mucormycosis coverage). Strong CYP3A4 inhibitor without significant CYP2C9/2C19 effect — narrower DDI profile than voriconazole. Delayed-release tablet improved absorption over the older suspension formulation.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 100, max: 400, typical: 300, unit: 'mg' } },
    half_life_hr: { 'PO': 35 },
    mw_g_mol: 700.79,
    refs: [],
  },

  // ── MACROLIDES — CYP3A4 inhibitors ────────────────────────────────
  {
    slug: 'erythromycin',
    name: 'Erythromycin',
    aliases: [],
    category: 'pharmacological',
    mechanism: 'Macrolide antibiotic — binds bacterial 50S ribosome blocking translocation. Strong CYP3A4 inhibitor + motilin receptor agonist (gastric prokinesia). DDI source: rises statin levels, prolongs QT via co-administered CYP3A4 substrates.',
    routes: ['PO', 'IV', 'TD'],
    doses: { 'PO': { min: 250, max: 500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 1.5 },
    mw_g_mol: 733.93,
    refs: [],
  },
  {
    slug: 'clarithromycin',
    name: 'Clarithromycin',
    aliases: ['Biaxin'],
    category: 'pharmacological',
    mechanism: '6-O-methyl erythromycin derivative — improved acid stability and tissue penetration. Strong CYP3A4 inhibitor (via 14-OH metabolite); first-line DDI perpetrator in clinical pharmacology. H. pylori eradication regimens.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    mw_g_mol: 747.95,
    refs: [],
  },

  // ── RIFAMYCINS — CYP3A4 + PXR inducers ────────────────────────────
  {
    slug: 'rifampin',
    name: 'Rifampin',
    aliases: ['Rifampicin', 'Rifadin'],
    category: 'pharmacological',
    mechanism: 'Bactericidal — binds bacterial RNA polymerase β-subunit. Most potent CYP3A4 inducer in clinical use (also CYP2C9, CYP2C19, CYP2B6, UGT, P-gp via PXR activation). Dramatically lowers warfarin, OCs, methadone, statins, transplant immunosuppressants, anti-HIV agents.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 300, max: 600, typical: 600, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 822.94,
    refs: [],
  },
  {
    slug: 'rifabutin',
    name: 'Rifabutin',
    aliases: ['Mycobutin'],
    category: 'pharmacological',
    mechanism: 'Spiropiperidyl rifamycin — narrower CYP3A4 induction than rifampin, used in HIV+TB co-treatment where rifampin would crater PI levels. Still meaningfully induces CYP3A4 (~40% AUC reduction of co-administered substrates).',
    routes: ['PO'],
    doses: { 'PO': { min: 150, max: 300, typical: 300, unit: 'mg' } },
    half_life_hr: { 'PO': 36 },
    mw_g_mol: 847.01,
    refs: [],
  },
  {
    slug: 'rifaximin',
    name: 'Rifaximin',
    aliases: ['Xifaxan'],
    category: 'pharmacological',
    mechanism: 'Non-absorbed rifamycin — minimal systemic exposure (<1% bioavailability) means minimal CYP induction despite same PXR mechanism. Used for travelers diarrhea, hepatic encephalopathy (gut ammonia), and IBS-D (gut microbiome modulation).',
    routes: ['PO'],
    doses: { 'PO': { min: 200, max: 550, typical: 400, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 785.88,
    refs: [],
  },

  // ── PROTEASE INHIBITOR / PK BOOSTER ───────────────────────────────
  {
    slug: 'ritonavir',
    name: 'Ritonavir',
    aliases: ['Norvir'],
    category: 'pharmacological',
    mechanism: 'HIV-1 protease inhibitor; modern use is as a PK booster (CYP3A4 inhibitor) for other PIs and Paxlovid. Most potent oral CYP3A4 inhibitor available. Major DDI source — extensive contraindication list (statins, ergots, sedatives, alpha-blockers).',
    routes: ['PO'],
    doses: { 'PO': { min: 100, max: 600, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 720.95,
    refs: [],
  },

  // ── CARDIOVASCULAR — antiarrhythmic with massive CYP profile ─────
  {
    slug: 'amiodarone',
    name: 'Amiodarone',
    aliases: ['Cordarone', 'Pacerone'],
    category: 'pharmacological',
    mechanism: 'Class III antiarrhythmic — multi-channel blocker (K+, Na+, Ca²⁺, β-adrenergic). Inhibits CYP3A4, CYP2C9, CYP2D6, P-gp — broad DDI profile. Massive Vd (~60 L/kg) and extreme half-life (~40-50 days) require months for steady-state and washout. Pulmonary, hepatic, thyroid toxicity at chronic exposure.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 100, max: 400, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 1080 },
    mw_g_mol: 645.31,
    refs: [],
  },
  {
    slug: 'carbamazepine',
    name: 'Carbamazepine',
    aliases: ['Tegretol'],
    category: 'pharmacological',
    mechanism: 'Voltage-gated sodium-channel blocker — first-line for partial epilepsy + trigeminal neuralgia. Potent CYP3A4 + CYP2C9 + UGT auto-inducer (own ke rises 2-3× by week 4). HLA-B*1502 + Asian ancestry → SJS/TEN risk. Major DDI source.',
    routes: ['PO'],
    doses: { 'PO': { min: 200, max: 1200, typical: 400, unit: 'mg' } },
    half_life_hr: { 'PO': 16 },
    mw_g_mol: 236.27,
    refs: [],
  },
  {
    slug: 'cimetidine',
    name: 'Cimetidine',
    aliases: ['Tagamet'],
    category: 'pharmacological',
    mechanism: 'H2 receptor antagonist — first H2 blocker to market; suppresses gastric acid via H2 → cAMP → parietal cell. Inhibits CYP1A2, CYP2D6, CYP3A4, CYP2C9 — substantially raises levels of theophylline, warfarin, phenytoin, propranolol. Largely supplanted by famotidine (no CYP DDI).',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 200, max: 800, typical: 400, unit: 'mg' } },
    half_life_hr: { 'PO': 2 },
    mw_g_mol: 252.34,
    refs: [],
  },

  // ── ARBs / ACEi / CCBs ────────────────────────────────────────────
  {
    slug: 'lisinopril',
    name: 'Lisinopril',
    aliases: ['Prinivil', 'Zestril'],
    category: 'pharmacological',
    mechanism: 'ACE inhibitor — blocks angiotensin I → II conversion in vascular endothelium. Lowers blood pressure, reduces afterload in heart failure, slows diabetic nephropathy. Renally cleared unchanged; no CYP metabolism. Cough (~10%) from bradykinin accumulation.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 40, typical: 20, unit: 'mg' } },
    half_life_hr: { 'PO': 12 },
    mw_g_mol: 405.49,
    refs: [],
  },
  {
    slug: 'losartan',
    name: 'Losartan',
    aliases: ['Cozaar'],
    category: 'pharmacological',
    mechanism: 'Angiotensin II AT1 receptor blocker — first ARB approved. Active E-3174 metabolite (via CYP2C9) drives most of the antihypertensive effect. Renally protective in diabetic nephropathy. No bradykinin-cough; useful where ACEi caused intolerance.',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 422.91,
    refs: [],
  },
  {
    slug: 'valsartan',
    name: 'Valsartan',
    aliases: ['Diovan'],
    category: 'pharmacological',
    mechanism: 'AT1 receptor blocker — no active metabolite (unlike losartan). Largely unchanged renal clearance; minimal CYP metabolism → fewer DDIs. Component of sacubitril/valsartan (Entresto) for HFrEF.',
    routes: ['PO'],
    doses: { 'PO': { min: 40, max: 320, typical: 160, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 435.52,
    refs: [],
  },
  {
    slug: 'amlodipine',
    name: 'Amlodipine',
    aliases: ['Norvasc'],
    category: 'pharmacological',
    mechanism: 'Long-acting dihydropyridine calcium-channel blocker — preferential vascular smooth-muscle Cav1.2 blockade with minimal cardiac effect. Lowers blood pressure via peripheral vasodilation. CYP3A4 substrate; weak inhibitor at higher doses. Pedal edema dose-related.',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 10, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 35 },
    mw_g_mol: 408.88,
    refs: [],
  },

  // ── DIURETICS ─────────────────────────────────────────────────────
  {
    slug: 'hydrochlorothiazide',
    name: 'Hydrochlorothiazide',
    aliases: ['HCTZ'],
    category: 'pharmacological',
    mechanism: 'Thiazide diuretic — inhibits Na+/Cl- cotransporter (NCC) in distal convoluted tubule of the kidney. First-line antihypertensive; mild Ca²⁺ retention reduces osteoporotic fractures vs loop diuretics. Hypokalemia + hyponatremia + hyperuricemia common.',
    routes: ['PO'],
    doses: { 'PO': { min: 12.5, max: 50, typical: 25, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 297.74,
    refs: [],
  },
  {
    slug: 'furosemide',
    name: 'Furosemide',
    aliases: ['Lasix'],
    category: 'pharmacological',
    mechanism: 'Loop diuretic — inhibits Na+/K+/2Cl- cotransporter (NKCC2) in thick ascending limb of loop of Henle. Most potent class of diuretic; cornerstone of CHF / pulmonary edema management. Ototoxicity at high IV bolus doses.',
    routes: ['PO', 'IV', 'IM'],
    doses: { 'PO': { min: 20, max: 80, typical: 40, unit: 'mg' } },
    half_life_hr: { 'PO': 2 },
    mw_g_mol: 330.74,
    refs: [],
  },
  {
    slug: 'spironolactone',
    name: 'Spironolactone',
    aliases: ['Aldactone'],
    category: 'pharmacological',
    mechanism: 'Aldosterone receptor antagonist (mineralocorticoid receptor) — K+-sparing diuretic; also weak androgen receptor antagonist (used off-label for acne, female-pattern hair loss, PCOS). Hyperkalemia risk; gynecomastia from anti-androgen activity.',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 200, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 1.5 },
    mw_g_mol: 416.57,
    refs: [],
  },

  // ── ANTIDIABETICS ─────────────────────────────────────────────────
  {
    slug: 'glipizide',
    name: 'Glipizide',
    aliases: ['Glucotrol'],
    category: 'pharmacological',
    mechanism: 'Second-generation sulfonylurea — closes pancreatic β-cell K-ATP channels → depolarization → Ca²⁺ influx → insulin release. Hypoglycemia risk + weight gain. CYP2C9 substrate; renal-safe relative to glyburide.',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 20, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 445.54,
    refs: [],
  },
  {
    slug: 'glimepiride',
    name: 'Glimepiride',
    aliases: ['Amaryl'],
    category: 'pharmacological',
    mechanism: 'Third-generation sulfonylurea — same K-ATP β-cell mechanism but lower hypoglycemia rate than glyburide. CYP2C9 substrate. Once-daily dosing.',
    routes: ['PO'],
    doses: { 'PO': { min: 1, max: 8, typical: 4, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    mw_g_mol: 490.62,
    refs: [],
  },
  {
    slug: 'glyburide',
    name: 'Glyburide',
    aliases: ['Glibenclamide', 'DiaBeta'],
    category: 'pharmacological',
    mechanism: 'Second-generation sulfonylurea — K-ATP channel closure → insulin release. Hepatically metabolized (CYP3A4); active M1 metabolite contributes to hypoglycemia in renal impairment. Beers-list problematic in elderly.',
    routes: ['PO'],
    doses: { 'PO': { min: 1.25, max: 20, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 10 },
    mw_g_mol: 494.00,
    refs: [],
  },
  {
    slug: 'pioglitazone',
    name: 'Pioglitazone',
    aliases: ['Actos'],
    category: 'pharmacological',
    mechanism: 'Thiazolidinedione — PPAR-γ agonist; sensitizes muscle, adipose, and liver to insulin. CYP2C8 substrate (gemfibrozil DDI). Weight gain + edema; bladder cancer signal in some studies; bone loss.',
    routes: ['PO'],
    doses: { 'PO': { min: 15, max: 45, typical: 30, unit: 'mg' } },
    half_life_hr: { 'PO': 7 },
    mw_g_mol: 356.44,
    refs: [],
  },
  {
    slug: 'saxagliptin',
    name: 'Saxagliptin',
    aliases: ['Onglyza'],
    category: 'pharmacological',
    mechanism: 'DPP-4 inhibitor — raises endogenous GLP-1 + GIP, promoting glucose-dependent insulin release. CYP3A4/5 substrate. Modest A1c reduction (~0.5%); slight heart failure signal vs sitagliptin.',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 5, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 315.41,
    refs: [],
  },

  // ── PDE5 INHIBITORS — CYP3A4 victims ──────────────────────────────
  {
    slug: 'sildenafil',
    name: 'Sildenafil',
    aliases: ['Viagra', 'Revatio'],
    category: 'pharmacological',
    mechanism: 'PDE5 inhibitor — raises cGMP in cavernosal smooth muscle → erectile vasodilation. CYP3A4 substrate (DDI with all azoles, ritonavir, grapefruit). Higher dose (Revatio) for pulmonary arterial hypertension.',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 474.58,
    refs: [],
  },
  {
    slug: 'tadalafil',
    name: 'Tadalafil',
    aliases: ['Cialis', 'Adcirca'],
    category: 'pharmacological',
    mechanism: 'PDE5 inhibitor with ~17h half-life — supports both on-demand and daily dosing. CYP3A4 substrate. Approved for erectile dysfunction, BPH, and pulmonary arterial hypertension.',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 20, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 17 },
    mw_g_mol: 389.40,
    refs: [],
  },
  {
    slug: 'vardenafil',
    name: 'Vardenafil',
    aliases: ['Levitra'],
    category: 'pharmacological',
    mechanism: 'PDE5 inhibitor — closer structural analog of sildenafil than tadalafil. CYP3A4 substrate. Greater PDE5 selectivity over PDE6 in vitro reduces visual side effects vs sildenafil.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 20, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 4.5 },
    mw_g_mol: 488.60,
    refs: [],
  },

  // ── PROTON PUMP INHIBITORS ────────────────────────────────────────
  {
    slug: 'omeprazole',
    name: 'Omeprazole',
    aliases: ['Prilosec'],
    category: 'pharmacological',
    mechanism: 'Irreversible H+/K+-ATPase inhibitor — covalently binds activated proton pumps in gastric parietal cells. CYP2C19 substrate (poor metabolizers have 5× higher AUC); also moderate CYP2C19 inhibitor (lowers clopidogrel activation).',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 20, max: 40, typical: 20, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 345.42,
    refs: [],
  },
  {
    slug: 'pantoprazole',
    name: 'Pantoprazole',
    aliases: ['Protonix'],
    category: 'pharmacological',
    mechanism: 'Irreversible H+/K+-ATPase inhibitor with the smallest CYP2C19 DDI footprint of the PPI class — least clopidogrel interaction. CYP2C19 substrate; metabolite further deactivated by sulfotransferase.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 20, max: 80, typical: 40, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 383.37,
    refs: [],
  },
  {
    slug: 'lansoprazole',
    name: 'Lansoprazole',
    aliases: ['Prevacid'],
    category: 'pharmacological',
    mechanism: 'Irreversible H+/K+-ATPase inhibitor. CYP2C19 + CYP3A4 substrate. Available OTC; commonly co-administered with NSAIDs to mitigate gastric ulcers.',
    routes: ['PO'],
    doses: { 'PO': { min: 15, max: 30, typical: 30, unit: 'mg' } },
    half_life_hr: { 'PO': 1.5 },
    mw_g_mol: 369.36,
    refs: [],
  },
  {
    slug: 'esomeprazole',
    name: 'Esomeprazole',
    aliases: ['Nexium'],
    category: 'pharmacological',
    mechanism: 'S-enantiomer of omeprazole — slower CYP2C19 metabolism than the racemate gives modestly higher steady-state AUC. Same H+/K+-ATPase mechanism. CYP2C19 inhibitor (clopidogrel DDI relevant).',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 20, max: 40, typical: 40, unit: 'mg' } },
    half_life_hr: { 'PO': 1.5 },
    mw_g_mol: 345.42,
    refs: [],
  },

  // ── H2 BLOCKERS ───────────────────────────────────────────────────
  {
    slug: 'famotidine',
    name: 'Famotidine',
    aliases: ['Pepcid'],
    category: 'pharmacological',
    mechanism: 'H2 receptor antagonist — suppresses gastric acid via H2 → cAMP → parietal cell. Renally cleared; no CYP metabolism → essentially no DDI footprint (preferred over cimetidine for this reason).',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 10, max: 40, typical: 20, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 337.45,
    refs: [],
  },
  {
    slug: 'ranitidine',
    name: 'Ranitidine',
    aliases: ['Zantac'],
    category: 'pharmacological',
    mechanism: 'H2 receptor antagonist — historically the highest-volume PO H2 blocker. Withdrawn 2020 due to NDMA contamination across the supply chain. Less CYP DDI than cimetidine but more than famotidine.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 75, max: 300, typical: 150, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 314.40,
    refs: [],
  },

  // ── ANTIBIOTICS ───────────────────────────────────────────────────
  {
    slug: 'amoxicillin',
    name: 'Amoxicillin',
    aliases: ['Amoxil'],
    category: 'pharmacological',
    mechanism: 'β-lactam — inhibits transpeptidase (PBP) crosslinking peptidoglycan in bacterial cell wall. Broader gram-negative coverage than penicillin. Renally cleared; no CYP. Allergy cross-reactivity with cephalosporins.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 1000, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 365.40,
    refs: [],
  },
  {
    slug: 'azithromycin',
    name: 'Azithromycin',
    aliases: ['Zithromax', 'Z-pak'],
    category: 'pharmacological',
    mechanism: 'Azalide macrolide — 50S ribosomal inhibitor; expanded gram-negative + atypical coverage vs erythromycin. Long tissue half-life supports 5-day dosing. Modest CYP3A4 inhibition (less than erythromycin/clarithromycin). QT prolongation signal at high doses.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 68 },
    mw_g_mol: 748.98,
    refs: [],
  },
  {
    slug: 'ciprofloxacin',
    name: 'Ciprofloxacin',
    aliases: ['Cipro'],
    category: 'pharmacological',
    mechanism: 'Fluoroquinolone — inhibits bacterial DNA gyrase + topoisomerase IV. Strong CYP1A2 inhibitor (raises caffeine, theophylline, tizanidine, clozapine). Black-box: tendinopathy + Achilles rupture, peripheral neuropathy, aortic aneurysm.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 750, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 331.34,
    refs: [],
  },
  {
    slug: 'doxycycline',
    name: 'Doxycycline',
    aliases: ['Vibramycin'],
    category: 'pharmacological',
    mechanism: 'Tetracycline — binds bacterial 30S ribosome blocking aminoacyl-tRNA. Used for CAP atypicals, rickettsial infections, acne, malaria prophylaxis. Photosensitivity; tooth discoloration in children <8.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 50, max: 200, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 18 },
    mw_g_mol: 444.43,
    refs: [],
  },
  {
    slug: 'metronidazole',
    name: 'Metronidazole',
    aliases: ['Flagyl'],
    category: 'pharmacological',
    mechanism: 'Nitroimidazole — anaerobic bacteria + protozoa reduce the nitro group to a cytotoxic radical that fragments DNA. Disulfiram-like reaction with alcohol. Modest CYP3A4 inhibition raises warfarin INR.',
    routes: ['PO', 'IV', 'TD'],
    doses: { 'PO': { min: 250, max: 750, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 171.16,
    refs: [],
  },

  // ── NSAIDS ────────────────────────────────────────────────────────
  {
    slug: 'diclofenac',
    name: 'Diclofenac',
    aliases: ['Voltaren'],
    category: 'pharmacological',
    mechanism: 'Acetic-acid NSAID — non-selective COX inhibitor with modest COX-2 preference. Higher cardiovascular risk than ibuprofen / naproxen. CYP2C9 substrate. Hepatotoxicity warning (~1:10,000).',
    routes: ['PO', 'TD', 'IM'],
    doses: { 'PO': { min: 25, max: 75, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 2 },
    mw_g_mol: 296.15,
    refs: [],
  },
  {
    slug: 'indomethacin',
    name: 'Indomethacin',
    aliases: ['Indocin'],
    category: 'pharmacological',
    mechanism: 'Indole-acetic NSAID — potent non-selective COX inhibitor. First-line for acute gout + pericarditis. High CNS penetration → headache, dizziness, confusion in elderly. CYP2C9 substrate.',
    routes: ['PO', 'IV', 'PR'],
    doses: { 'PO': { min: 25, max: 75, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 4.5 },
    mw_g_mol: 357.79,
    refs: [],
  },
  {
    slug: 'meloxicam',
    name: 'Meloxicam',
    aliases: ['Mobic'],
    category: 'pharmacological',
    mechanism: 'Enolic-acid NSAID — preferential COX-2 inhibitor at low doses (lower GI bleed signal than non-selective NSAIDs). Long half-life supports once-daily dosing. CYP2C9 substrate.',
    routes: ['PO', 'IV', 'IM'],
    doses: { 'PO': { min: 7.5, max: 15, typical: 15, unit: 'mg' } },
    half_life_hr: { 'PO': 20 },
    mw_g_mol: 351.40,
    refs: [],
  },

  // ── ANTISEIZURE ───────────────────────────────────────────────────
  {
    slug: 'lamotrigine',
    name: 'Lamotrigine',
    aliases: ['Lamictal'],
    category: 'pharmacological',
    mechanism: 'Voltage-gated sodium-channel blocker — also weak Ca²⁺-channel + glutamate-release modulation. First-line for focal epilepsy + bipolar maintenance (mood stabilizer). UGT1A4 substrate (valproate doubles half-life). SJS/TEN risk → mandatory 6-week titration.',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 400, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 25 },
    mw_g_mol: 256.09,
    refs: [],
  },
  {
    slug: 'valproate',
    name: 'Valproate',
    aliases: ['Valproic acid', 'Depakote'],
    category: 'pharmacological',
    mechanism: 'GABA-mimetic — raises CNS GABA via GABA-T inhibition; also blocks voltage-gated Na+ channels and modulates Ca²⁺. Broad-spectrum antiseizure + bipolar + migraine prophylaxis. Strong CYP2C9 inhibitor + UGT inhibitor (raises lamotrigine 2×). Teratogenic (NTDs); mitochondrial toxicity in young children.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 2000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 144.21,
    refs: [],
  },
  {
    slug: 'gabapentin',
    name: 'Gabapentin',
    aliases: ['Neurontin'],
    category: 'pharmacological',
    mechanism: 'α2δ subunit of voltage-gated Ca²⁺ channels — reduces excitatory neurotransmitter release. Used for neuropathic pain + adjunctive seizure therapy + RLS. Renally cleared; no CYP. Dose-dependent absorption (saturable LAT1) — high-dose AUC plateaus.',
    routes: ['PO'],
    doses: { 'PO': { min: 100, max: 1200, typical: 600, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 171.24,
    refs: [],
  },
  {
    slug: 'pregabalin',
    name: 'Pregabalin',
    aliases: ['Lyrica'],
    category: 'pharmacological',
    mechanism: 'α2δ Ca²⁺-channel ligand (same target as gabapentin) — better-defined PK with linear absorption (no saturable transporter). Approved for neuropathic pain, fibromyalgia, post-herpetic neuralgia, focal seizures. Schedule V (mild euphoria + abuse signal).',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 600, typical: 150, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 159.23,
    refs: [],
  },
  {
    slug: 'topiramate',
    name: 'Topiramate',
    aliases: ['Topamax'],
    category: 'pharmacological',
    mechanism: 'Multi-target antiseizure — blocks Na+ + Ca²⁺ channels, enhances GABA-A, antagonizes AMPA / kainate, weak carbonic anhydrase inhibition. Migraine prophylaxis + weight-loss combination (Qsymia). Cognitive slowing, paresthesias, kidney stones (CA inhibition).',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 400, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 21 },
    mw_g_mol: 339.36,
    refs: [],
  },

  // ── TRIPTANS / GEPANTS ────────────────────────────────────────────
  {
    slug: 'sumatriptan',
    name: 'Sumatriptan',
    aliases: ['Imitrex'],
    category: 'pharmacological',
    mechanism: '5-HT1B/1D agonist — constricts cranial blood vessels and inhibits trigeminal nerve neuropeptide release. First-line abortive migraine therapy. Coronary vasoconstriction concern in CAD. SC formulation has fastest onset (~10 min).',
    routes: ['PO', 'SC', 'IN'],
    doses: { 'PO': { min: 25, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 2.5 },
    mw_g_mol: 295.40,
    refs: [],
  },
  {
    slug: 'rizatriptan',
    name: 'Rizatriptan',
    aliases: ['Maxalt'],
    category: 'pharmacological',
    mechanism: '5-HT1B/1D agonist — second-generation triptan; faster oral onset and higher receptor potency than sumatriptan. Orally disintegrating tablet useful when migraine causes nausea. MAO-A substrate (dose adjust with propranolol).',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 10, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 2 },
    mw_g_mol: 269.35,
    refs: [],
  },

  // ── ANTIHISTAMINES — second-generation, low-sedating ──────────────
  {
    slug: 'loratadine',
    name: 'Loratadine',
    aliases: ['Claritin'],
    category: 'pharmacological',
    mechanism: 'Second-generation H1 antagonist — minimal BBB penetration → low sedation. Active descarboethoxy metabolite (desloratadine) has long half-life supporting once-daily dosing.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 10, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 382.88,
    refs: [],
  },
  {
    slug: 'cetirizine',
    name: 'Cetirizine',
    aliases: ['Zyrtec'],
    category: 'pharmacological',
    mechanism: 'Second-generation H1 antagonist — carboxylic acid form of hydroxyzine; reduced BBB penetration but slightly more sedating than loratadine / fexofenadine. Renally cleared.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 10, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 388.89,
    refs: [],
  },
  {
    slug: 'fexofenadine',
    name: 'Fexofenadine',
    aliases: ['Allegra'],
    category: 'pharmacological',
    mechanism: 'Second-generation H1 antagonist — active metabolite of terfenadine (pulled from market for QT). No CNS sedation; no QT signal. P-glycoprotein substrate (grapefruit juice lowers F).',
    routes: ['PO'],
    doses: { 'PO': { min: 60, max: 180, typical: 180, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 501.66,
    refs: [],
  },

  // ── ASTHMA / COPD ─────────────────────────────────────────────────
  {
    slug: 'salbutamol',
    name: 'Salbutamol',
    aliases: ['Albuterol', 'Ventolin'],
    category: 'pharmacological',
    mechanism: 'Short-acting β2-adrenergic agonist (SABA) — relaxes bronchial smooth muscle via Gs/cAMP pathway. First-line bronchodilator for acute asthma. Tachycardia + tremor at high inhaled doses; greater systemic effect with nebulized administration.',
    routes: ['INH', 'PO', 'IV'],
    doses: { 'INH': { min: 0.1, max: 0.4, typical: 0.2, unit: 'mg' } },
    half_life_hr: { 'INH': 4 },
    mw_g_mol: 239.31,
    refs: [],
  },
  {
    slug: 'fluticasone',
    name: 'Fluticasone',
    aliases: ['Flovent', 'Flonase'],
    category: 'pharmacological',
    mechanism: 'Inhaled / intranasal corticosteroid — high topical glucocorticoid receptor potency; near-zero systemic bioavailability after inhalation due to first-pass metabolism. First-line maintenance therapy for asthma + allergic rhinitis. CYP3A4 substrate (ritonavir DDI causes systemic Cushing\'s).',
    routes: ['INH', 'IN'],
    doses: { 'INH': { min: 0.05, max: 0.5, typical: 0.2, unit: 'mg' } },
    half_life_hr: { 'INH': 8 },
    mw_g_mol: 444.51,
    refs: [],
  },
  {
    slug: 'budesonide',
    name: 'Budesonide',
    aliases: ['Pulmicort', 'Entocort'],
    category: 'pharmacological',
    mechanism: 'Glucocorticoid — used inhaled for asthma maintenance, intranasally for allergic rhinitis, and orally as a delayed-release (Entocort) for ileal Crohn\'s with high first-pass metabolism reducing systemic effect.',
    routes: ['INH', 'IN', 'PO'],
    doses: { 'INH': { min: 0.2, max: 1.6, typical: 0.4, unit: 'mg' } },
    half_life_hr: { 'INH': 3 },
    mw_g_mol: 430.54,
    refs: [],
  },
  {
    slug: 'montelukast',
    name: 'Montelukast',
    aliases: ['Singulair'],
    category: 'pharmacological',
    mechanism: 'Leukotriene CysLT1 receptor antagonist — blocks LTD4 / LTE4 bronchoconstriction. Adjunctive asthma + allergic rhinitis. FDA black-box (2020) for neuropsychiatric adverse events including suicidality.',
    routes: ['PO'],
    doses: { 'PO': { min: 4, max: 10, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 586.18,
    refs: [],
  },
  {
    slug: 'ipratropium',
    name: 'Ipratropium',
    aliases: ['Atrovent'],
    category: 'pharmacological',
    mechanism: 'Quaternary ammonium muscarinic antagonist — bronchodilation via M3 blockade in airway smooth muscle. Quaternary structure limits systemic absorption from inhaled route. Combined with salbutamol (Combivent) for acute COPD.',
    routes: ['INH'],
    doses: { 'INH': { min: 0.02, max: 0.04, typical: 0.04, unit: 'mg' } },
    half_life_hr: { 'INH': 2 },
    mw_g_mol: 332.46,
    refs: [],
  },

  // ── ANTIPSYCHOTICS ────────────────────────────────────────────────
  {
    slug: 'risperidone',
    name: 'Risperidone',
    aliases: ['Risperdal'],
    category: 'pharmacological',
    mechanism: 'Atypical antipsychotic — D2 + 5-HT2A receptor antagonist. CYP2D6 substrate; active 9-OH metabolite (paliperidone) drives much of the effect. Schizophrenia, bipolar, and autism-associated irritability.',
    routes: ['PO', 'IM'],
    doses: { 'PO': { min: 0.5, max: 6, typical: 2, unit: 'mg' } },
    half_life_hr: { 'PO': 20 },
    mw_g_mol: 410.49,
    refs: [],
  },
  {
    slug: 'haloperidol',
    name: 'Haloperidol',
    aliases: ['Haldol'],
    category: 'pharmacological',
    mechanism: 'High-potency typical antipsychotic — strong D2 antagonist with minimal anticholinergic / antihistamine activity. EPS + tardive dyskinesia risk; QT prolongation at high IV doses. CYP3A4 + CYP2D6 substrate. IM decanoate enables monthly depot dosing.',
    routes: ['PO', 'IM', 'IV'],
    doses: { 'PO': { min: 0.5, max: 30, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 18 },
    mw_g_mol: 375.86,
    refs: [],
  },

  // ── OTHER HIGH-PRIORITY ───────────────────────────────────────────
  {
    slug: 'lithium',
    name: 'Lithium',
    aliases: ['Lithobid', 'Eskalith'],
    category: 'pharmacological',
    mechanism: 'Monovalent cation — exact mechanism unclear; inhibits GSK-3β, IMPase (depleting myo-inositol), and modulates neurotransmitter release. First-line mood stabilizer for bipolar maintenance + suicidality reduction. Narrow therapeutic index (0.6–1.2 mEq/L) — TDM mandatory. Renal-cleared; thiazides + ACEi raise levels.',
    routes: ['PO'],
    doses: { 'PO': { min: 300, max: 1800, typical: 900, unit: 'mg' } },
    half_life_hr: { 'PO': 24 },
    mw_g_mol: 6.94,
    refs: [],
  },
  {
    slug: 'naltrexone',
    name: 'Naltrexone',
    aliases: ['Vivitrol', 'ReVia'],
    category: 'pharmacological',
    mechanism: 'Pure µ-opioid receptor antagonist — competitive blockade with no agonist activity. Approved for alcohol use disorder + opioid use disorder relapse prevention. Hepatotoxicity warning at high doses (>300 mg/d). LDN at 1–4.5 mg used off-label for autoimmune / fibromyalgia.',
    routes: ['PO', 'IM'],
    doses: { 'PO': { min: 25, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 341.40,
    refs: [],
  },
  {
    slug: 'ondansetron',
    name: 'Ondansetron',
    aliases: ['Zofran'],
    category: 'pharmacological',
    mechanism: '5-HT3 receptor antagonist — blocks vagal afferent emetic signaling from the GI tract + chemoreceptor trigger zone. First-line for chemotherapy-induced + post-operative nausea. CYP3A4/2D6 substrate. QT prolongation at IV doses ≥ 16 mg.',
    routes: ['PO', 'IV', 'IM'],
    doses: { 'PO': { min: 4, max: 24, typical: 8, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 293.36,
    refs: [],
  },
  {
    slug: 'metoclopramide',
    name: 'Metoclopramide',
    aliases: ['Reglan'],
    category: 'pharmacological',
    mechanism: 'Dopamine D2 antagonist (CTZ + GI tract) + 5-HT4 agonist + 5-HT3 antagonist. Antiemetic + prokinetic for diabetic gastroparesis. EPS + tardive dyskinesia risk → black-box warning at chronic use > 12 weeks.',
    routes: ['PO', 'IV', 'IM'],
    doses: { 'PO': { min: 5, max: 15, typical: 10, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    mw_g_mol: 299.80,
    refs: [],
  },
  {
    slug: 'loperamide',
    name: 'Loperamide',
    aliases: ['Imodium'],
    category: 'pharmacological',
    mechanism: 'Peripheral µ-opioid agonist — slows gut motility via enteric neurons; P-glycoprotein efflux at the BBB keeps CNS exposure minimal at therapeutic doses. Abused at megadoses for euphoria — cardiotoxicity (QT, torsades) emerged as the predominant overdose harm.',
    routes: ['PO'],
    doses: { 'PO': { min: 2, max: 16, typical: 4, unit: 'mg' } },
    half_life_hr: { 'PO': 11 },
    mw_g_mol: 477.04,
    refs: [],
  },

  // ── ANTICOAGULANT — heparin (LMWH skipped — biologic-ish polymer) ─
  {
    slug: 'clopidogrel',
    name: 'Clopidogrel',
    aliases: ['Plavix'],
    category: 'pharmacological',
    mechanism: 'Thienopyridine antiplatelet prodrug — CYP2C19-mediated activation to thiol metabolite that irreversibly blocks platelet P2Y12 ADP receptor. CYP2C19 poor metabolizers + PPI co-administration reduce activation, lowering antiplatelet effect (clinically meaningful with omeprazole/esomeprazole; less with pantoprazole).',
    routes: ['PO'],
    doses: { 'PO': { min: 75, max: 75, typical: 75, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 321.82,
    refs: [],
  },
];

function main(): void {
  const data = JSON.parse(readFileSync(COMPOUNDS_PATH, 'utf-8')) as Array<Record<string, unknown>>;
  const bySlug = new Map(data.map(c => [c['slug'] as string, c]));

  let added = 0;
  let skipped = 0;
  for (const stub of STUBS) {
    if (bySlug.has(stub.slug)) {
      skipped++;
      continue;
    }
    data.push(stub as unknown as Record<string, unknown>);
    bySlug.set(stub.slug, stub as unknown as Record<string, unknown>);
    added++;
  }

  writeFileSync(COMPOUNDS_PATH, JSON.stringify(data, null, 2) + '\n');

  console.log('\nWave 0b first sub-batch — top prescribed-meds stubs:');
  console.log(`  Added: ${added}`);
  console.log(`  Skipped (already present): ${skipped}`);
  console.log(`  Catalog: ${data.length} compounds`);
  console.log(`\nNext: run scripts/authoring/2026-05-02-systems-tagging.ts to land system tags.`);
}

main();
