/**
 * 2026-05-03-wave-0b-attainable-2.ts — Wave 0b sub-batch 8.
 *
 * Continues the attainable-focus push toward 1000:
 *   - Research peptides (setmelanotide, KPV, adropin, larazotide)
 *   - Biohacker / longevity compounds (methylene-blue, 5-amino-1MQ,
 *     tesofensine)
 *   - Remaining common Rx: tapentadol, buprenorphine, more PPIs,
 *     eplerenone, felodipine, antiarrhythmics, more LAMAs/LABAs,
 *     acarbose, hydroxyzine, buspirone
 *   - Popular botanical supplements: pycnogenol, grape-seed, cinnamon,
 *     capsaicin, fenugreek, tribulus, icariin, black-seed oil,
 *     sea-buckthorn, royal jelly, propolis
 *   - Mineral subforms (zinc + magnesium variants, sodium chloride)
 *   - OTC topicals (chlorhexidine, fluoride, ciclopirox, efinaconazole,
 *     permethrin)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const COMPOUNDS_PATH = join(__dirname, '..', '..', 'packages', 'registry', 'data', 'compounds.json');

type Stub = {
  slug: string;
  name: string;
  aliases: string[];
  category: string;
  mechanism: string;
  routes: string[];
  doses: Record<string, { min: number; max: number; typical: number; unit?: string }>;
  half_life_hr: Record<string, number>;
  mw_g_mol?: number;
  refs: string[];
};

const STUBS: Stub[] = [
  // ── RESEARCH / SPECIALTY PEPTIDES ─────────────────────────────────
  {
    slug: 'setmelanotide',
    name: 'Setmelanotide',
    aliases: ['Imcivree'],
    category: 'peptide',
    mechanism: 'MC4R-selective melanocortin agonist — restores hypothalamic POMC pathway signaling in genetic obesity from POMC, PCSK1, LEPR, or BBS deficiency. FDA-approved for these specific monogenic obesities + Bardet-Biedl syndrome. Hyperpigmentation + erection (MC1R + MC4R cross) are class effects.',
    routes: ['SC'],
    doses: { 'SC': { min: 1, max: 3, typical: 3, unit: 'mg' } },
    half_life_hr: { 'SC': 11 },
    mw_g_mol: 1117.32,
    refs: [],
  },
  {
    slug: 'kpv',
    name: 'KPV',
    aliases: ['Lys-Pro-Val'],
    category: 'peptide',
    mechanism: 'C-terminal tripeptide of α-MSH — anti-inflammatory in the gut without the pigment-stimulating activity of full MSH. Research peptide for IBD, colitis, leaky gut. Putative downregulation of NF-κB + reduction of IL-1, IL-6, TNF-α.',
    routes: ['PO', 'SC'],
    doses: { 'PO': { min: 0.2, max: 1, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 342.44,
    refs: [],
  },
  {
    slug: 'adropin',
    name: 'Adropin',
    aliases: ['ENHO'],
    category: 'peptide',
    mechanism: 'Liver / brain-secreted 76-residue peptide hormone (the active 34-aa C-terminal fragment is what circulates). Insulin-sensitizing + endothelial protective; low levels associate with metabolic syndrome. Research-stage; no clinical product yet.',
    routes: ['SC', 'IV'],
    doses: { 'SC': { min: 0.5, max: 5, typical: 2, unit: 'mg' } },
    half_life_hr: { 'SC': 1 },
    refs: [],
  },
  {
    slug: 'larazotide',
    name: 'Larazotide',
    aliases: ['AT-1001'],
    category: 'peptide',
    mechanism: 'Zonulin antagonist octapeptide — blocks zonulin-induced tight-junction disassembly in gut epithelium. Trialed for celiac disease as adjunct to gluten-free diet (failed Phase 3 in 2022); biohacker / leaky-gut interest persists.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.25, max: 1, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    refs: [],
  },
  {
    slug: 'tesofensine',
    name: 'Tesofensine',
    aliases: ['NS-2330'],
    category: 'pharmacological',
    mechanism: 'Triple monoamine reuptake inhibitor (DAT + NET + SERT). Originally trialed for Alzheimer + Parkinson, abandoned, then resurrected for obesity — Phase 2 weight loss ~10% at 6 months. Approved in Mexico / Argentina for obesity; not FDA-approved.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.25, max: 1, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'PO': 220 },
    mw_g_mol: 343.85,
    refs: [],
  },

  // ── BIOHACKER / RESEARCH SMALL-MOLECULE COMPOUNDS ────────────────
  {
    slug: 'methylene-blue',
    name: 'Methylene Blue',
    aliases: ['Methylthioninium chloride'],
    category: 'pharmacological',
    mechanism: 'Phenothiazine dye — at low doses (0.5–4 mg/kg) acts as a mitochondrial alternate electron carrier (cytochrome c shunt) + MAO-A inhibitor. Used clinically for methemoglobinemia + ifosfamide encephalopathy. Biohacker interest in low-dose for cognition + mitochondrial support; serotonin syndrome risk with SSRIs at higher doses.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 0.5, max: 4, typical: 1, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    mw_g_mol: 319.85,
    refs: [],
  },
  {
    slug: '5-amino-1mq',
    name: '5-Amino-1MQ',
    aliases: ['NNMT inhibitor'],
    category: 'other',
    mechanism: 'Selective NNMT (nicotinamide N-methyltransferase) inhibitor — preserves cellular methyl donor (SAM) + NAD+ pools by preventing NAD-precursor sink. Mouse studies show fat-mass reduction + insulin sensitization. Research-chem availability outpaces clinical evidence.',
    routes: ['PO'],
    doses: { 'PO': { min: 100, max: 300, typical: 150, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 159.19,
    refs: [],
  },

  // ── MORE COMMON RX ────────────────────────────────────────────────
  {
    slug: 'tapentadol',
    name: 'Tapentadol',
    aliases: ['Nucynta'],
    category: 'pharmacological',
    mechanism: 'Centrally-acting μ-opioid agonist + norepinephrine reuptake inhibitor — dual mechanism gives analgesic effect with lower opioid receptor occupancy than equipotent morphine, reducing GI side effects. Schedule II. CYP-independent metabolism (UGT2B7) limits DDI footprint.',
    routes: ['PO'],
    doses: { 'PO': { min: 50, max: 250, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 221.34,
    refs: [],
  },
  {
    slug: 'buprenorphine',
    name: 'Buprenorphine',
    aliases: ['Subutex', 'Suboxone (with naloxone)', 'Belbuca'],
    category: 'pharmacological',
    mechanism: 'Partial μ-opioid agonist + κ-opioid antagonist — ceiling effect on respiratory depression makes it safer than full agonists. Workhorse of opioid use disorder maintenance therapy + chronic pain (sublingual film, buccal film, patch). Precipitates withdrawal if started while still on full agonists.',
    routes: ['SL', 'TD', 'IV', 'IM'],
    doses: { 'SL': { min: 2, max: 24, typical: 16, unit: 'mg' } },
    half_life_hr: { 'SL': 30 },
    mw_g_mol: 467.65,
    refs: [],
  },
  {
    slug: 'dexlansoprazole',
    name: 'Dexlansoprazole',
    aliases: ['Dexilant'],
    category: 'pharmacological',
    mechanism: 'R-enantiomer of lansoprazole — proton pump inhibitor with delayed dual-release formulation (peaks at 1–2h and 4–5h) that extends acid suppression vs once-released PPIs. Approved for GERD + erosive esophagitis. CYP2C19 substrate.',
    routes: ['PO'],
    doses: { 'PO': { min: 30, max: 60, typical: 60, unit: 'mg' } },
    half_life_hr: { 'PO': 1.5 },
    mw_g_mol: 369.36,
    refs: [],
  },
  {
    slug: 'rabeprazole',
    name: 'Rabeprazole',
    aliases: ['Aciphex'],
    category: 'pharmacological',
    mechanism: 'Proton pump inhibitor — H+/K+-ATPase irreversible inhibitor. Less CYP2C19-dependent metabolism than omeprazole; relative DDI advantage with clopidogrel. Available OTC in some markets.',
    routes: ['PO'],
    doses: { 'PO': { min: 20, max: 60, typical: 20, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 359.44,
    refs: [],
  },
  {
    slug: 'eplerenone',
    name: 'Eplerenone',
    aliases: ['Inspra'],
    category: 'pharmacological',
    mechanism: 'Selective mineralocorticoid receptor antagonist — fewer anti-androgenic / progestational side effects than spironolactone (no gynecomastia). Approved for HFrEF post-MI + resistant hypertension. Hyperkalemia risk; CYP3A4 substrate (avoid with strong inhibitors).',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 50, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    mw_g_mol: 414.49,
    refs: [],
  },
  {
    slug: 'felodipine',
    name: 'Felodipine',
    aliases: ['Plendil'],
    category: 'pharmacological',
    mechanism: 'Dihydropyridine CCB — vascular Cav1.2 blockade > cardiac selectivity ratio higher than amlodipine. Once-daily extended-release dosing for hypertension. Grapefruit juice raises AUC ~2× via intestinal CYP3A4 inhibition (the canonical grapefruit-DDI example).',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 10, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 384.25,
    refs: [],
  },
  {
    slug: 'mexiletine',
    name: 'Mexiletine',
    aliases: ['Mexitil'],
    category: 'pharmacological',
    mechanism: 'Class IB antiarrhythmic — voltage-gated Na+ channel blocker preferentially binding the inactivated state. Used for ventricular arrhythmias + neuropathic pain (off-label) + myotonic syndromes. CYP2D6 substrate.',
    routes: ['PO'],
    doses: { 'PO': { min: 150, max: 300, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 11 },
    mw_g_mol: 179.26,
    refs: [],
  },
  {
    slug: 'flecainide',
    name: 'Flecainide',
    aliases: ['Tambocor'],
    category: 'pharmacological',
    mechanism: 'Class IC antiarrhythmic — strong Na+ channel blocker with slow dissociation. "Pill-in-pocket" approach for paroxysmal atrial fibrillation in structurally normal hearts. Pro-arrhythmic in ischemic heart disease (CAST trial 1989) — contraindicated post-MI.',
    routes: ['PO'],
    doses: { 'PO': { min: 50, max: 400, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 414.34,
    refs: [],
  },
  {
    slug: 'metolazone',
    name: 'Metolazone',
    aliases: ['Zaroxolyn'],
    category: 'pharmacological',
    mechanism: 'Thiazide-like diuretic — same NCC blockade as HCTZ but works synergistically with loop diuretics in diuretic-resistant heart failure. Powerful natriuresis when sequentially blocking distal tubule downstream of loop-treated proximal segments.',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 20, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 365.83,
    refs: [],
  },
  {
    slug: 'aclidinium',
    name: 'Aclidinium',
    aliases: ['Tudorza'],
    category: 'pharmacological',
    mechanism: 'Inhaled long-acting muscarinic antagonist (LAMA) — quaternary ammonium for minimal systemic exposure. Twice-daily dosing for COPD maintenance. Rapid plasma hydrolysis vs tiotropium\'s slow dissociation drives the dosing-frequency difference.',
    routes: ['INH'],
    doses: { 'INH': { min: 0.4, max: 0.4, typical: 0.4, unit: 'mg' } },
    half_life_hr: { 'INH': 2 },
    mw_g_mol: 564.77,
    refs: [],
  },
  {
    slug: 'umeclidinium',
    name: 'Umeclidinium',
    aliases: ['Incruse Ellipta'],
    category: 'pharmacological',
    mechanism: 'Inhaled LAMA — once-daily M3-preferring muscarinic antagonist for COPD. Component of triple-therapy inhalers (Trelegy = umeclidinium + vilanterol + fluticasone furoate). Quaternary structure limits systemic absorption.',
    routes: ['INH'],
    doses: { 'INH': { min: 0.0625, max: 0.0625, typical: 0.0625, unit: 'mg' } },
    half_life_hr: { 'INH': 11 },
    mw_g_mol: 508.55,
    refs: [],
  },
  {
    slug: 'vilanterol',
    name: 'Vilanterol',
    aliases: [],
    category: 'pharmacological',
    mechanism: 'Long-acting β2-adrenergic agonist — 24-h once-daily dosing (longest LABA available). Always combined with inhaled corticosteroid (fluticasone furoate) or LAMA (umeclidinium) for asthma + COPD maintenance — never as monotherapy in asthma.',
    routes: ['INH'],
    doses: { 'INH': { min: 0.025, max: 0.025, typical: 0.025, unit: 'mg' } },
    half_life_hr: { 'INH': 11 },
    mw_g_mol: 486.43,
    refs: [],
  },
  {
    slug: 'indacaterol',
    name: 'Indacaterol',
    aliases: ['Arcapta'],
    category: 'pharmacological',
    mechanism: 'Once-daily ultra-long-acting β2-adrenergic agonist (LABA) for COPD. Faster onset than salmeterol (~5 min) makes it dual rescue + maintenance role. Cough on inhalation in 17–25% — formulation-related, often resolves with continued use.',
    routes: ['INH'],
    doses: { 'INH': { min: 0.075, max: 0.3, typical: 0.15, unit: 'mg' } },
    half_life_hr: { 'INH': 40 },
    mw_g_mol: 392.49,
    refs: [],
  },
  {
    slug: 'dofetilide',
    name: 'Dofetilide',
    aliases: ['Tikosyn'],
    category: 'pharmacological',
    mechanism: 'Class III antiarrhythmic — selective IKr blockade prolongs cardiac repolarization. Approved for AF rhythm control. Mandatory 3-day inpatient initiation (TdP risk during loading); strict CrCl-based dosing + numerous CYP3A4 / OCT2 inhibitor contraindications.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.125, max: 0.5, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'PO': 10 },
    mw_g_mol: 441.56,
    refs: [],
  },
  {
    slug: 'acarbose',
    name: 'Acarbose',
    aliases: ['Precose', 'Glucobay'],
    category: 'pharmacological',
    mechanism: 'α-Glucosidase inhibitor — competitively blocks intestinal brush-border α-glucosidases delaying carbohydrate digestion → blunts post-prandial glucose spike. Modest A1c reduction (~0.5%); GI side effects (flatulence, bloating, diarrhea) limit adherence. Researcher interest in longevity (extended lifespan in male mice in NIA ITP).',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 2 },
    mw_g_mol: 645.61,
    refs: [],
  },
  {
    slug: 'hydroxyzine',
    name: 'Hydroxyzine',
    aliases: ['Atarax', 'Vistaril'],
    category: 'pharmacological',
    mechanism: 'First-generation H1 antagonist with anxiolytic + sedating + antiemetic activity. Common alternative to benzodiazepines for anxiety due to no addiction potential. Anticholinergic burden — Beers-list problematic. Cetirizine is the active metabolite.',
    routes: ['PO', 'IM'],
    doses: { 'PO': { min: 25, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 20 },
    mw_g_mol: 374.91,
    refs: [],
  },
  {
    slug: 'buspirone',
    name: 'Buspirone',
    aliases: ['Buspar'],
    category: 'pharmacological',
    mechanism: '5-HT1A partial agonist — generalized anxiety treatment without GABA-A activation, so no sedation, no abuse, no addiction. Onset over weeks like an SSRI; acute anxiety relief is poor. CYP3A4 substrate.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 60, typical: 30, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 385.51,
    refs: [],
  },

  // ── POPULAR BOTANICAL SUPPLEMENTS ─────────────────────────────────
  {
    slug: 'pycnogenol',
    name: 'Pycnogenol',
    aliases: ['Pine bark extract', 'Pinus pinaster extract'],
    category: 'adaptogen',
    mechanism: 'Standardized French maritime pine bark extract (~65–75% procyanidins). Trialed for vascular endothelial function (raises eNOS-derived NO), chronic venous insufficiency, ADHD adjunct. Modest BP / endothelial benefit in meta-analyses.',
    routes: ['PO'],
    doses: { 'PO': { min: 50, max: 360, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    refs: [],
  },
  {
    slug: 'grape-seed-extract',
    name: 'Grape Seed Extract',
    aliases: ['Vitis vinifera seed extract'],
    category: 'polyphenol',
    mechanism: 'Standardized procyanidin-rich extract. Antioxidant + endothelial vasodilator effects. Clinical evidence weakest for cardiovascular endpoints; better signal for chronic venous insufficiency + UV skin protection.',
    routes: ['PO', 'TD'],
    doses: { 'PO': { min: 100, max: 600, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    refs: [],
  },
  {
    slug: 'cinnamaldehyde',
    name: 'Cinnamaldehyde',
    aliases: ['Cinnamon active'],
    category: 'terpenoid',
    mechanism: 'Primary aromatic aldehyde of cinnamon (Cinnamomum verum / cassia). Insulin-sensitizing in vitro + modest fasting-glucose / A1c reduction in T2D meta-analyses. Cassia variety is high in coumarin (hepatotoxicity at chronic high intake); Ceylon cinnamon is preferred for supplementation.',
    routes: ['PO'],
    doses: { 'PO': { min: 250, max: 6000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 132.16,
    refs: [],
  },
  {
    slug: 'capsaicin',
    name: 'Capsaicin',
    aliases: ['Capsicum', 'Chili extract'],
    category: 'alkaloid',
    mechanism: 'TRPV1 agonist — initial activation produces burning sensation; chronic exposure desensitizes nociceptors → topical analgesia for neuropathic pain (post-herpetic, diabetic neuropathy). Oral capsicum used for thermogenic / metabolic supplementation; modest effect.',
    routes: ['TD', 'PO'],
    doses: { 'TD': { min: 0.025, max: 8, typical: 0.075, unit: 'mg' } },
    half_life_hr: { 'TD': 24 },
    mw_g_mol: 305.41,
    refs: [],
  },
  {
    slug: 'fenugreek',
    name: 'Fenugreek',
    aliases: ['Trigonella foenum-graecum'],
    category: 'adaptogen',
    mechanism: 'Seed extract; saponins (diosgenin, fenuside), 4-hydroxyisoleucine, and trigonelline as named actives. Modest blood-glucose lowering + LDL reduction. Marketed for testosterone support — RCTs mixed, possibly via aromatase inhibition.',
    routes: ['PO'],
    doses: { 'PO': { min: 500, max: 2000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    refs: [],
  },
  {
    slug: 'tribulus',
    name: 'Tribulus Terrestris',
    aliases: ['Puncture vine'],
    category: 'adaptogen',
    mechanism: 'Saponin-rich extract (protodioscin standardized). Marketed for testosterone + libido; multiple RCTs show no testosterone effect in men, slight libido improvement in postmenopausal women. Animal studies suggest NO-mediated erectile effect via androgen-independent pathway.',
    routes: ['PO'],
    doses: { 'PO': { min: 250, max: 1500, typical: 750, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    refs: [],
  },
  {
    slug: 'icariin',
    name: 'Icariin',
    aliases: ['Epimedium / horny goat weed extract'],
    category: 'flavonoid',
    mechanism: 'Prenylated flavonoid from Epimedium species. Weak PDE5 inhibition + estrogenic activity; mechanistic basis for the traditional erectile / libido + osteoporosis indications. Bioavailability poor; deglycosylated icaritin has higher absorption.',
    routes: ['PO'],
    doses: { 'PO': { min: 250, max: 1000, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 676.66,
    refs: [],
  },
  {
    slug: 'nigella-sativa',
    name: 'Nigella Sativa',
    aliases: ['Black seed', 'Black cumin oil', 'Thymoquinone source'],
    category: 'adaptogen',
    mechanism: 'Seed oil; thymoquinone is the dominant active. Anti-inflammatory + antimicrobial + modest BP / lipid / glycemic effects in meta-analyses. Asthma, atopic dermatitis, and metabolic syndrome RCTs show small benefits.',
    routes: ['PO', 'TD'],
    doses: { 'PO': { min: 500, max: 2000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    refs: [],
  },
  {
    slug: 'sea-buckthorn-oil',
    name: 'Sea Buckthorn Oil',
    aliases: ['Hippophae rhamnoides oil'],
    category: 'adaptogen',
    mechanism: 'Berry / seed oil with rare palmitoleic acid (ω-7) content. Anti-inflammatory + skin-barrier support; modest evidence for atopic dermatitis + sicca symptoms. Often used topically + orally for skin/mucosal hydration.',
    routes: ['PO', 'TD'],
    doses: { 'PO': { min: 500, max: 3000, typical: 2000, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    refs: [],
  },
  {
    slug: 'royal-jelly',
    name: 'Royal Jelly',
    aliases: [],
    category: 'adaptogen',
    mechanism: 'Bee-secreted nutritive substance with high 10-hydroxy-2-decenoic acid (10-HDA) content. Marketed for menopausal symptoms, immune support, fertility — clinical evidence weak. Allergenic in atopic individuals (anaphylaxis case reports).',
    routes: ['PO'],
    doses: { 'PO': { min: 100, max: 3000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    refs: [],
  },
  {
    slug: 'propolis',
    name: 'Propolis',
    aliases: ['Bee glue'],
    category: 'adaptogen',
    mechanism: 'Resinous bee-product mixture; CAPE (caffeic acid phenethyl ester) + galangin + pinocembrin as named actives. Antimicrobial + anti-inflammatory in topical / oral applications (cold sores, oral aphthous ulcers, mild burns). Bee-allergen cross-reactivity.',
    routes: ['PO', 'TD'],
    doses: { 'PO': { min: 250, max: 1500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    refs: [],
  },

  // ── MINERAL SUBFORMS ──────────────────────────────────────────────
  {
    slug: 'zinc-citrate',
    name: 'Zinc Citrate',
    aliases: [],
    category: 'mineral',
    mechanism: 'Zinc chelated to citrate. Bioavailability comparable to zinc gluconate (~20–25%); preferred form in some lozenge formulations for upper respiratory infections. ~31% elemental Zn by weight.',
    routes: ['PO'],
    doses: { 'PO': { min: 15, max: 50, typical: 25, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 574.34,
    refs: [],
  },
  {
    slug: 'zinc-gluconate',
    name: 'Zinc Gluconate',
    aliases: [],
    category: 'mineral',
    mechanism: 'Zinc chelated to gluconate. ~14% elemental Zn by weight. Common in cold-shortening lozenges (Cochrane meta-analysis: ~33% reduction in cold duration with ≥75 mg elemental Zn within 24h of onset).',
    routes: ['PO'],
    doses: { 'PO': { min: 15, max: 50, typical: 25, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 455.69,
    refs: [],
  },
  {
    slug: 'zinc-acetate',
    name: 'Zinc Acetate',
    aliases: [],
    category: 'mineral',
    mechanism: 'Zinc chelated to acetate. ~30% elemental Zn. Used both as a cold-lozenge zinc source and as the chronic copper-chelation therapy for Wilson disease (Galzin) by blocking enterocyte copper uptake.',
    routes: ['PO'],
    doses: { 'PO': { min: 25, max: 50, typical: 25, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 219.51,
    refs: [],
  },
  {
    slug: 'magnesium-orotate',
    name: 'Magnesium Orotate',
    aliases: [],
    category: 'mineral',
    mechanism: 'Mg²⁺ chelated to orotic acid. Lower elemental-Mg content (~7%) but the orotate moiety is a pyrimidine-synthesis intermediate sometimes claimed to enhance cardiac uptake. Trialed in HFrEF (Stepura 2009) with modest mortality signal — replication is limited.',
    routes: ['PO'],
    doses: { 'PO': { min: 1500, max: 6000, typical: 3000, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 334.46,
    refs: [],
  },
  {
    slug: 'magnesium-chloride',
    name: 'Magnesium Chloride',
    aliases: ['MgCl2'],
    category: 'mineral',
    mechanism: 'Inorganic Mg²⁺ salt — high elemental Mg (~12%), high water solubility, used IV in eclampsia + arrhythmias. Topical "magnesium oil" claims poor evidence for transdermal absorption. Laxative effect at high oral doses.',
    routes: ['PO', 'IV', 'TD'],
    doses: { 'PO': { min: 200, max: 800, typical: 300, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 95.21,
    refs: [],
  },
  {
    slug: 'sodium-chloride',
    name: 'Sodium Chloride',
    aliases: ['Table salt', 'NaCl', 'Saline'],
    category: 'mineral',
    mechanism: 'Essential electrolyte — IV saline for resuscitation + hypertonic saline (3%) for severe hyponatremia + ICP. Oral salt tablets for sodium-loss states (POTS, dysautonomia, ultra-endurance, primary aldosteronism management). Hypertension sensitivity in salt-sensitive individuals.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 500, max: 6000, typical: 2300, unit: 'mg' } },
    half_life_hr: { 'PO': 24 },
    mw_g_mol: 58.44,
    refs: [],
  },

  // ── OTC TOPICALS / DENTAL ─────────────────────────────────────────
  {
    slug: 'chlorhexidine',
    name: 'Chlorhexidine',
    aliases: ['Peridex', 'Hibiclens'],
    category: 'topical',
    mechanism: 'Cationic biguanide antiseptic — disrupts bacterial cell membranes; strongly binds oral mucosa and dental pellicle giving ≥12h sustained activity. Oral rinse for periodontitis + post-surgical dental hygiene; surgical scrub formulation. Mild reversible tooth staining at chronic use.',
    routes: ['TD'],
    doses: { 'TD': { min: 6, max: 25, typical: 18, unit: 'mg' } },
    half_life_hr: { 'TD': 12 },
    mw_g_mol: 505.45,
    refs: [],
  },
  {
    slug: 'sodium-fluoride',
    name: 'Sodium Fluoride',
    aliases: ['Topical fluoride', 'NaF'],
    category: 'topical',
    mechanism: 'Topical / dietary fluoride source — incorporates into hydroxyapatite as fluorapatite, hardening enamel and resisting demineralization. Toothpaste at 1000–1500 ppm; prescription 5000 ppm for high-caries patients; community water fluoridation at 0.7 ppm.',
    routes: ['TD', 'PO'],
    doses: { 'TD': { min: 0.5, max: 5, typical: 1.5, unit: 'mg' } },
    half_life_hr: { 'TD': 4 },
    mw_g_mol: 41.99,
    refs: [],
  },
  {
    slug: 'ciclopirox',
    name: 'Ciclopirox',
    aliases: ['Loprox', 'Penlac'],
    category: 'topical',
    mechanism: 'Hydroxypyridone antifungal — chelates polyvalent metal cations (Fe³⁺, Al³⁺) blocking fungal mitochondrial enzymes. Topical for tinea + nail-lacquer formulation for onychomycosis. Slow nail-bed delivery requires 6-12 month course.',
    routes: ['TD'],
    doses: { 'TD': { min: 1, max: 80, typical: 8, unit: 'mg' } },
    half_life_hr: { 'TD': 24 },
    mw_g_mol: 207.27,
    refs: [],
  },
  {
    slug: 'efinaconazole',
    name: 'Efinaconazole',
    aliases: ['Jublia'],
    category: 'topical',
    mechanism: 'Triazole topical antifungal — fungal CYP51 inhibitor with optimized nail-keratin penetration. FDA-approved for onychomycosis with higher mycologic cure rate than ciclopirox lacquer. 48-week course for full toenail clearing.',
    routes: ['TD'],
    doses: { 'TD': { min: 10, max: 10, typical: 10, unit: 'mg' } },
    half_life_hr: { 'TD': 24 },
    mw_g_mol: 348.39,
    refs: [],
  },
  {
    slug: 'permethrin',
    name: 'Permethrin',
    aliases: ['Elimite', 'Nix'],
    category: 'topical',
    mechanism: 'Pyrethroid neurotoxin for arthropods — prolongs Na+ channel opening at insect / arachnid synapses → paralysis + death. Topical 1% for head lice, 5% for scabies. Mammalian toxicity is low (Na+ channel selectivity favors insects).',
    routes: ['TD'],
    doses: { 'TD': { min: 5, max: 60, typical: 30, unit: 'mg' } },
    half_life_hr: { 'TD': 24 },
    mw_g_mol: 391.30,
    refs: [],
  },

  // ── MORE OTC / SPECIALTY ──────────────────────────────────────────
  {
    slug: 'pancrelipase',
    name: 'Pancrelipase',
    aliases: ['Creon', 'Zenpep'],
    category: 'pharmacological',
    mechanism: 'Porcine pancreatic enzyme replacement (lipase, amylase, protease mix) — taken with meals in pancreatic exocrine insufficiency (cystic fibrosis, chronic pancreatitis, pancreatic cancer). Enteric-coated minispheres release in alkaline duodenum.',
    routes: ['PO'],
    doses: { 'PO': { min: 10000, max: 80000, typical: 40000, unit: 'IU' } },
    half_life_hr: { 'PO': 1 },
    refs: [],
  },
  {
    slug: 'desmopressin',
    name: 'Desmopressin',
    aliases: ['DDAVP'],
    category: 'peptide',
    mechanism: 'Synthetic vasopressin (V2-selective) analog — antidiuretic via renal collecting-duct V2R but minimal V1 vasopressor effect. Used for central diabetes insipidus, nocturnal enuresis, von Willebrand factor release in mild type-1 vWD (acute hemostasis).',
    routes: ['IN', 'PO', 'IV', 'SC', 'SL'],
    doses: { 'IN': { min: 0.01, max: 0.04, typical: 0.02, unit: 'mg' } },
    half_life_hr: { 'IN': 3 },
    mw_g_mol: 1069.22,
    refs: [],
  },
  {
    slug: 'finasteride-topical',
    name: 'Finasteride (topical)',
    aliases: [],
    category: 'topical',
    mechanism: 'Topical 0.25% formulation for androgenetic alopecia — same 5α-reductase type II inhibition as oral finasteride but with much lower systemic exposure (<5%) → reduced sexual / cognitive side-effect signal. Compounded or specialty-pharmacy product.',
    routes: ['TD'],
    doses: { 'TD': { min: 0.5, max: 2.5, typical: 1, unit: 'mg' } },
    half_life_hr: { 'TD': 6 },
    mw_g_mol: 372.55,
    refs: [],
  },
  {
    slug: 'oral-contraceptive-combo',
    name: 'Combined Oral Contraceptive (placeholder)',
    aliases: ['COC'],
    category: 'hormone',
    mechanism: 'Class entry — typically 20-35 mcg ethinyl estradiol + a progestin (norethindrone, levonorgestrel, drospirenone, desogestrel). Tracked separately by their components (already in registry); this entry exists for users to log "I take a combined OCP" without specifying brand.',
    routes: ['PO'],
    doses: { 'PO': { min: 1, max: 1, typical: 1, unit: 'mg' } },
    half_life_hr: { 'PO': 24 },
    refs: [],
  },
  {
    slug: 'progestin-only-pill',
    name: 'Progestin-Only Pill',
    aliases: ['POP', 'Mini-pill'],
    category: 'hormone',
    mechanism: 'Class entry — usually norethindrone 0.35 mg or drospirenone 4 mg. Mechanism: cervical mucus thickening + endometrial atrophy; ovulation suppression less consistent than COC. Used when estrogen is contraindicated (lactation, VTE history, migraine with aura).',
    routes: ['PO'],
    doses: { 'PO': { min: 0.35, max: 4, typical: 0.35, unit: 'mg' } },
    half_life_hr: { 'PO': 9 },
    refs: [],
  },
];

function main(): void {
  const data = JSON.parse(readFileSync(COMPOUNDS_PATH, 'utf-8')) as Array<Record<string, unknown>>;
  const bySlug = new Map(data.map(c => [c['slug'] as string, c]));

  let added = 0;
  let skipped = 0;
  for (const stub of STUBS) {
    if (bySlug.has(stub.slug)) {
      skipped++;
      continue;
    }
    data.push(stub as unknown as Record<string, unknown>);
    bySlug.set(stub.slug, stub as unknown as Record<string, unknown>);
    added++;
  }

  writeFileSync(COMPOUNDS_PATH, JSON.stringify(data, null, 2) + '\n');

  console.log('\nWave 0b sub-batch 8 — attainable continuation:');
  console.log(`  Added: ${added}`);
  console.log(`  Skipped (already present): ${skipped}`);
  console.log(`  Catalog: ${data.length} compounds`);
}

main();
