/**
 * 2026-05-24-signaling-batch-I.ts
 *
 * step.note grind, batch I — 6 pathways. Refs title-checked via esummary
 * 2026-05-24; notes-only except serotonin_5ht2a (its TrkB step cites
 * "Moliner 2023" — that PMID confirmed via esearch and added):
 *   bradykinin_kallikrein_kinin   PMID:15705422 (Adv Immunol), 8673930
 *   microbiome_scfa_butyrate      PMID:9406136, 33906079
 *   serotonin_5ht2a_psychedelic_signaling  PMID:26841800 (Nichols PharmRev) + ADD 37280397 (Moliner 2023 Nat Neurosci)
 *   gsh_redox_cycle_antioxidant   PMID:23201771 (Glutathione peroxidases)
 *   mglur_metabotropic_glutamate  PMID:20055706 (ARPT mGluR review)
 *   serotonin_receptor_pharmacology  PMID:26841800, 10462127 (central 5-HT review)
 * NOTE: serotonin_receptor_pharmacology "5ht-receptor-activation -> serotonin"
 *   is a back-edge loop (flagged for restructuring) — not annotated here.
 * Exact from→to keys (mismatch throws); idempotent.
 *   tsx scripts/authoring/2026-05-24-signaling-batch-I.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PATHWAYS_PATH = join(__dirname, '..', '..', 'packages', 'registry', 'data', 'pathways.json');

const BATCH: Array<{ slug: string; addRefs?: string[]; notes: Record<string, string> }> = [
  {
    slug: 'bradykinin_kallikrein_kinin',
    notes: {
      'HMWK (plasma) + factor XII / prekallikrein bradykinin (nonapeptide) — Arg-Pro-Pro-Gly-Phe-Ser-Pro-Phe-Arg':
        'Bradykinin is generated by the plasma kallikrein-kinin (contact) system: activated factor XII converts ' +
        'prekallikrein to kallikrein, which cleaves high-molecular-weight kininogen (HMWK) to release the ' +
        'nonapeptide bradykinin. This contact-activation cascade ties the kinin system to coagulation and to ' +
        'inflammation.',
      'LMWK (tissue) kallidin (Lys-bradykinin, decapeptide)':
        'A parallel tissue system uses tissue kallikrein on low-molecular-weight kininogen to produce kallidin ' +
        '(Lys-bradykinin), a decapeptide. Aminopeptidases can convert kallidin to bradykinin, so the two systems ' +
        'feed a shared pool of active kinins acting on the same receptors.',
      'bradykinin B2R activation (constitutive)':
        'Bradykinin acts mainly through the B2 receptor, a constitutively expressed GPCR. B2R drives vasodilation ' +
        '(via endothelial NO and prostacyclin), increased vascular permeability, and pain — the classic signs of ' +
        'inflammation, and the receptor behind ACE-inhibitor angioedema and cough.',
      'des-Arg9-bradykinin (inflammation) B1R activation (induced)':
        'Carboxypeptidases remove the C-terminal Arg to form des-Arg9-bradykinin, which activates the B1 receptor. ' +
        'Unlike B2R, B1R is barely expressed normally but is strongly induced by inflammation and cytokines — so ' +
        'the kinin system shifts toward a B1-mediated response in chronic inflammation and injury.',
      'bradykinin inactive degradation products':
        'Kinins are very short-lived, rapidly inactivated by kininases — chiefly ACE (kininase II) and ' +
        'carboxypeptidases — to inactive fragments. This rapid degradation keeps kinin signaling local and ' +
        'transient, so inhibiting the degrading enzymes markedly potentiates bradykinin’s effects.',
      'ACE inhibition (captopril etc.) bradykinin accumulation':
        'Because ACE both makes angiotensin II and degrades bradykinin, ACE inhibitors (captopril and others) ' +
        'cause bradykinin to accumulate. This adds to their vasodilatory benefit but also causes the ' +
        'characteristic dry cough and the risk of angioedema — bradykinin-mediated, not angiotensin-mediated.',
      'C1-INH deficiency (HAE) unrestrained plasma kallikrein → bradykinin storm':
        'C1-esterase inhibitor (C1-INH) is the key brake on plasma kallikrein and factor XIIa. When deficient ' +
        '(hereditary angioedema), the contact system runs unchecked, producing a bradykinin “storm” and recurrent ' +
        'angioedema. This is why HAE is treated by blocking kallikrein (lanadelumab) or B2R (icatibant), not with ' +
        'antihistamines.',
    },
  },
  {
    slug: 'microbiome_scfa_butyrate',
    notes: {
      'dietary fiber + resistant starch (escape SI absorption) colonic delivery (cecum + proximal colon)':
        'Dietary fiber and resistant starch escape digestion in the small intestine and reach the colon intact, ' +
        'delivering fermentable substrate to the dense microbial community of the cecum and proximal colon. This ' +
        'delivery of otherwise-indigestible carbohydrate to gut bacteria is what feeds SCFA production — the basis ' +
        'of fiber’s benefits.',
      'fiber + resistant starch (colon) SCFAs (acetate, propionate, butyrate)':
        'Colonic bacteria ferment these carbohydrates to short-chain fatty acids — chiefly acetate, propionate, ' +
        'and butyrate (roughly 60:20:20). SCFAs are the major end-products of fiber fermentation and the principal ' +
        'currency through which the microbiome communicates with host metabolism and immunity.',
      'butyrate (colonocyte) mitochondrial β-oxidation → acetyl-CoA → ATP':
        'Butyrate is the preferred fuel of colonocytes: they take it up and run it through mitochondrial ' +
        'β-oxidation to acetyl-CoA and ATP. This local fuel use keeps the colonic epithelium in a low-oxygen state ' +
        'that favors beneficial anaerobes — and butyrate deficiency impairs epithelial barrier integrity.',
      'butyrate / propionate HDAC inhibition → histone hyperacetylation':
        'At signaling concentrations, butyrate and propionate inhibit histone deacetylases (HDACs), increasing ' +
        'histone acetylation and reprogramming gene expression. This epigenetic action drives anti-inflammatory ' +
        'effects (notably promoting colonic regulatory T cells) — a major mechanism of SCFAs’ immunomodulation.',
      'acetate / propionate GPR43 / GPR41 (FFAR2/3) on L-cells':
        'Acetate and propionate are ligands at the GPCRs GPR43 (FFAR2) and GPR41 (FFAR3) on enteroendocrine ' +
        'L-cells and other tissues. Activating them stimulates gut-hormone secretion (GLP-1, PYY), linking fiber ' +
        'intake to appetite regulation, insulin secretion, and energy balance.',
      'butyrate GPR109A (HCA2) on macrophages + colonocytes':
        'Butyrate is the main ligand for GPR109A (HCA2) on colonocytes and macrophages — the same receptor niacin ' +
        'activates. Signaling here drives anti-inflammatory and anti-carcinogenic programs in the colon, one ' +
        'reason butyrate is protective against colitis and colorectal cancer.',
      'SCFAs (luminal) portal venous spillover → systemic':
        'SCFAs not used locally enter the portal vein and reach the liver and systemic circulation, where ' +
        'propionate is gluconeogenic and SCFAs influence hepatic lipid metabolism, appetite centers, and immune ' +
        'cells far from the gut. This is how a colonic fermentation product exerts whole-body effects.',
    },
  },
  {
    slug: 'serotonin_5ht2a_psychedelic_signaling',
    addRefs: ['PMID:37280397'],
    notes: {
      'psilocybin (PO) psilocin (active)':
        'Psilocybin is a prodrug: intestinal and blood phosphatases rapidly dephosphorylate it to psilocin, the ' +
        'actual psychoactive molecule. This conversion is why oral psilocybin has a delayed, smoother onset than ' +
        'psilocin itself, and underlies its dosing in clinical trials for depression.',
      'psilocin / LSD / DMT 5-HT2A receptor activation (Gq biased)':
        'The classic psychedelics — psilocin, LSD, DMT — act as agonists at the 5-HT2A serotonin receptor, the ' +
        'necessary target for their subjective effects (blocked by the antagonist ketanserin). They engage Gq ' +
        'signaling with a distinctive profile that may distinguish hallucinogenic from non-hallucinogenic 5-HT2A ' +
        'agonists.',
      '5-HT2A → Gq → PLC IP3 + DAG → Ca²⁺ + PKC':
        '5-HT2A couples to Gq, activating phospholipase C to generate IP3 and DAG — raising intracellular Ca²⁺ and ' +
        'activating PKC. On cortical pyramidal neurons this is excitatory, and the resulting signaling is the ' +
        'proximal trigger for the downstream glutamatergic and plasticity effects of psychedelics.',
      'cortical pyramidal glutamate release mGluR2/3 + AMPA modulation':
        '5-HT2A activation on layer-5 cortical pyramidal neurons increases glutamate release, engaging AMPA ' +
        'receptors and presynaptic mGluR2/3. This cortical glutamate surge is thought to underlie the perceptual ' +
        'effects, and the mGluR2/3 interaction is why mGluR2 agonists can dampen psychedelic effects.',
      'psilocin / LSD TrkB direct binding (Moliner 2023)':
        'Beyond 5-HT2A, psychedelics were shown to bind the BDNF receptor TrkB directly (Moliner et al. 2023), ' +
        'promoting neurotrophic signaling and plasticity. This receptor action — distinct from the 5-HT2A-mediated ' +
        'subjective trip — may help explain the lasting antidepressant, pro-plasticity effects.',
      'sustained 5-HT2A → mTOR PFC synaptogenesis (24–48 h)':
        'Sustained 5-HT2A signaling activates mTOR-dependent protein synthesis, driving structural synaptogenesis ' +
        '(new dendritic spines) in the prefrontal cortex over ~24-48 h. This delayed plasticity, rather than the ' +
        'acute experience, is increasingly seen as the substrate of psychedelics’ durable therapeutic effects.',
    },
  },
  {
    slug: 'gsh_redox_cycle_antioxidant',
    notes: {
      '2 GSH + H₂O₂ GSSG + 2 H₂O':
        'Glutathione peroxidases (GPx) use two molecules of reduced glutathione (GSH) to reduce hydrogen peroxide ' +
        'to water, oxidizing GSH to the disulfide GSSG. This is the cell’s main enzymatic defense against H₂O₂, ' +
        'complementing catalase and the peroxiredoxins — a key node in redox homeostasis.',
      'GSH + phospholipid-OOH GSSG + phospholipid-OH':
        'The same GPx system (notably the membrane-acting GPx4) reduces lipid hydroperoxides in phospholipids to ' +
        'harmless alcohols, again consuming GSH. This lipid-repair function protects membranes from peroxidative ' +
        'damage — and its failure is precisely what drives ferroptotic cell death.',
      'GSSG + NADPH + H+ 2 GSH + NADP+':
        'GSSG is recycled back to GSH by glutathione reductase, which uses NADPH as the electron donor. This ' +
        'regeneration keeps the GSH:GSSG ratio very high (reducing), letting the system buffer continuous oxidant ' +
        'production — so NADPH supply is the ultimate limit on antioxidant capacity.',
      'glucose-6-phosphate + NADP+ 6-phosphogluconolactone + NADPH':
        'The NADPH powering GSH regeneration comes largely from the pentose phosphate pathway: glucose-6-phosphate ' +
        'dehydrogenase (G6PD) oxidizes G6P while reducing NADP⁺ to NADPH. This is why G6PD deficiency causes ' +
        'oxidant-induced hemolysis — red cells cannot regenerate GSH to defend against oxidative stress.',
      'GSH/GSSG ratio falls Nrf2 release from Keap1 → ARE transcription':
        'The GSH/GSSG couple is also a signal: when the ratio falls (oxidative stress), oxidation of sensor ' +
        'cysteines on Keap1 releases Nrf2 to drive ARE-dependent antioxidant genes. So the glutathione system both ' +
        'buffers oxidants directly and triggers an adaptive transcriptional defense.',
    },
  },
  {
    slug: 'mglur_metabotropic_glutamate',
    notes: {
      'glutamate (synaptic spillover) mGluR I (mGluR1, mGluR5) — postsynaptic Gq':
        'Group I mGluRs (mGluR1, mGluR5) sit postsynaptically and couple to Gq — so unlike the inhibitory groups ' +
        'they are generally excitatory, raising Ca²⁺ and enhancing NMDA-receptor function. mGluR5 is a major ' +
        'target in fragile X syndrome and is studied in anxiety and addiction.',
      'glutamate (presynaptic autoreceptor) mGluR II (mGluR2, mGluR3) — Gi/o':
        'Group II mGluRs (mGluR2, mGluR3) act largely as presynaptic autoreceptors coupled to Gi/o, suppressing ' +
        'further glutamate release — a negative-feedback brake on excitatory transmission. This is why mGluR2/3 ' +
        'agonists are anxiolytic and were trialed in schizophrenia and anxiety.',
      'glutamate (presynaptic + retinal ON) mGluR III (mGluR4/6/7/8) — Gi/o':
        'Group III mGluRs (mGluR4/6/7/8), also Gi/o-coupled, are mostly presynaptic; mGluR6 is the exception, ' +
        'mediating the sign-inverting glutamate response of retinal ON-bipolar cells. The group adds presynaptic ' +
        'inhibitory control and is a target in Parkinson’s (mGluR4) and retinal signaling.',
      'mGluR2 activation 5-HT2A psychedelic effect dampening':
        'Group II mGluR2 cross-talks with the psychedelic target 5-HT2A: the two form receptor complexes, and ' +
        'mGluR2 activation dampens 5-HT2A-driven cortical excitation. This interaction is one reason mGluR2/3 ' +
        'agonists blunt psychedelic effects and links the glutamate and serotonin systems in cortex.',
      'NMDA blockade (ketamine) glutamate burst → AMPA → mGluR cross-talk':
        'Ketamine (an NMDA-receptor blocker) triggers a downstream glutamate burst that activates AMPA receptors ' +
        'and engages mGluR signaling, driving rapid synaptogenesis. This AMPA/mGluR cross-talk is part of the ' +
        'leading model for ketamine’s fast antidepressant action — convergent with the plasticity mechanism of ' +
        'psychedelics.',
    },
  },
  {
    slug: 'serotonin_receptor_pharmacology',
    notes: {
      'tryptophan 5-hydroxytryptophan':
        'Serotonin synthesis starts with the essential amino acid tryptophan, hydroxylated by tryptophan ' +
        'hydroxylase (TPH) to 5-hydroxytryptophan (5-HTP). This is the rate-limiting step, and TPH exists as two ' +
        'isoforms — TPH1 (gut/periphery) and TPH2 (brain) — so central and peripheral serotonin are made ' +
        'separately.',
      '5-hydroxytryptophan serotonin':
        '5-HTP is decarboxylated by aromatic L-amino-acid decarboxylase (AADC) to serotonin (5-HT). Because most ' +
        'body serotonin is made in the gut (enterochromaffin cells) and serotonin does not cross the blood-brain ' +
        'barrier, the brain must synthesize its own — a key fact for understanding serotonergic drugs.',
      'serotonin 5ht-receptor-activation':
        'Serotonin acts on a large family of receptors (5-HT1 through 5-HT7), almost all GPCRs except the ' +
        'ionotropic 5-HT3. This diversity — subtypes coupling to different G proteins in different tissues — is ' +
        'why serotonergic drugs have such varied effects (e.g. 5-HT3 antagonists for nausea, 5-HT1B/1D agonists ' +
        'for migraine).',
      'serotonin melatonin':
        'In the pineal gland at night, serotonin is converted to melatonin by AANAT (the rate-limiting enzyme) ' +
        'and ASMT. This links the serotonin system to circadian output — serotonin is the daytime precursor ' +
        'rhythmically transformed into the “darkness hormone” melatonin.',
    },
  },
];

const data: Array<{ slug: string; steps: Array<{ from: string; to: string; note?: string }>; refs?: string[] }> =
  JSON.parse(readFileSync(PATHWAYS_PATH, 'utf8'));

let totalAdded = 0;
let totalRefs = 0;
for (const { slug, notes, addRefs } of BATCH) {
  const pw = data.find(p => p.slug === slug);
  if (!pw) throw new Error(`pathway "${slug}" not found`);
  const used = new Set<string>();
  let added = 0;
  for (const step of pw.steps) {
    const key = `${step.from} ${step.to}`;
    const note = notes[key];
    if (note === undefined) continue;
    used.add(key);
    if (step.note) continue;
    if (note.length > 500) throw new Error(`${slug} "${key}": note ${note.length} > 500 chars`);
    step.note = note;
    added++;
  }
  const missing = Object.keys(notes).filter(k => !used.has(k));
  if (missing.length) throw new Error(`${slug}: note key(s) matched no step: ${missing.join(' | ')}`);
  if (addRefs?.length) {
    pw.refs = pw.refs ?? [];
    for (const r of addRefs) if (!pw.refs.includes(r)) { pw.refs.push(r); totalRefs++; }
  }
  console.log(`${slug}: added ${added} step notes${addRefs?.length ? ` (+${addRefs.length} ref)` : ''}`);
  totalAdded += added;
}

writeFileSync(PATHWAYS_PATH, JSON.stringify(data, null, 2) + '\n');
console.log(`batch I total: ${totalAdded} notes, ${totalRefs} refs`);
