/**
 * 2026-05-03-wave-0b-benzos-cardio-bone.ts — Wave 0b sub-batch 9.
 *
 * Closes more attainable-Rx gaps:
 *   - Benzodiazepines (alprazolam, clonazepam, lorazepam, diazepam,
 *     temazepam, oxazepam) + reversal (flumazenil) + phenobarbital
 *   - Cardiovascular: clonidine, methyldopa, α1-blockers (doxazosin,
 *     terazosin, prazosin), labetalol, nimodipine, propafenone
 *   - Anti-seizure: levetiracetam, oxcarbazepine, phenytoin (already)
 *   - Bisphosphonates: alendronate, risedronate, ibandronate,
 *     zoledronate, pamidronate
 *   - More opioids: pentazocine, nalbuphine, butorphanol
 *   - More allergy/asthma: cromolyn, zafirlukast, zileuton,
 *     beclomethasone, ciclesonide
 *   - More antivirals: ganciclovir, valganciclovir, famciclovir,
 *     entecavir, baloxavir
 *   - More antibiotics: linezolid, ertapenem, cefuroxime, cefdinir,
 *     sulfasalazine
 *   - GI motility: linaclotide, lubiprostone, diphenoxylate-atropine
 *   - Misc Rx: hydroquinone, calcipotriene, crisaborole, fulvestrant
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const COMPOUNDS_PATH = join(__dirname, '..', '..', 'packages', 'registry', 'data', 'compounds.json');

type Stub = {
  slug: string;
  name: string;
  aliases: string[];
  category: string;
  mechanism: string;
  routes: string[];
  doses: Record<string, { min: number; max: number; typical: number; unit?: string }>;
  half_life_hr: Record<string, number>;
  mw_g_mol?: number;
  refs: string[];
};

const STUBS: Stub[] = [
  // ── BENZODIAZEPINES ───────────────────────────────────────────────
  {
    slug: 'alprazolam',
    name: 'Alprazolam',
    aliases: ['Xanax'],
    category: 'pharmacological',
    mechanism: 'Triazolo-benzodiazepine — GABA-A α1/α2/α3/α5 positive allosteric modulator. Fast onset, short half-life make it the highest-misuse-potential benzodiazepine. Approved for panic disorder + generalized anxiety. CYP3A4 substrate. Schedule IV; difficult to taper after chronic use.',
    routes: ['PO', 'SL'],
    doses: { 'PO': { min: 0.25, max: 4, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'PO': 12 },
    mw_g_mol: 308.77,
    refs: [],
  },
  {
    slug: 'clonazepam',
    name: 'Clonazepam',
    aliases: ['Klonopin'],
    category: 'pharmacological',
    mechanism: 'Long-acting benzodiazepine — GABA-A positive allosteric modulator with strong anxiolytic + anticonvulsant + muscle-relaxant effects. Approved for panic, atypical seizures (Lennox-Gastaut, absence). Schedule IV; less euphoria than alprazolam but similar dependence at chronic use.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.25, max: 4, typical: 1, unit: 'mg' } },
    half_life_hr: { 'PO': 35 },
    mw_g_mol: 315.71,
    refs: [],
  },
  {
    slug: 'lorazepam',
    name: 'Lorazepam',
    aliases: ['Ativan'],
    category: 'pharmacological',
    mechanism: 'Intermediate-acting benzodiazepine. Hepatic glucuronidation (no CYP) makes it safer in liver disease + DDI-light. IV use for status epilepticus + alcohol withdrawal. Outpatient anxiety + acute panic.',
    routes: ['PO', 'IV', 'IM', 'SL'],
    doses: { 'PO': { min: 0.5, max: 4, typical: 1, unit: 'mg' } },
    half_life_hr: { 'PO': 12 },
    mw_g_mol: 321.16,
    refs: [],
  },
  {
    slug: 'diazepam',
    name: 'Diazepam',
    aliases: ['Valium'],
    category: 'pharmacological',
    mechanism: 'Long-acting benzodiazepine. Active metabolites (nordazepam, temazepam, oxazepam) extend effective half-life to days. Workhorse for alcohol withdrawal protocols, status epilepticus rescue, muscle spasticity, procedural sedation. CYP3A4 + CYP2C19 substrate.',
    routes: ['PO', 'IV', 'IM', 'PR'],
    doses: { 'PO': { min: 2, max: 40, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 60 },
    mw_g_mol: 284.74,
    refs: [],
  },
  {
    slug: 'temazepam',
    name: 'Temazepam',
    aliases: ['Restoril'],
    category: 'pharmacological',
    mechanism: 'Intermediate-acting benzodiazepine targeted at sleep onset + maintenance. Glucuronide metabolism (no CYP) → DDI-light. Less hangover than long-acting benzodiazepines. Schedule IV; chronic use carries dependence + cognitive risk in elderly.',
    routes: ['PO'],
    doses: { 'PO': { min: 7.5, max: 30, typical: 15, unit: 'mg' } },
    half_life_hr: { 'PO': 11 },
    mw_g_mol: 300.74,
    refs: [],
  },
  {
    slug: 'oxazepam',
    name: 'Oxazepam',
    aliases: ['Serax'],
    category: 'pharmacological',
    mechanism: 'Intermediate-acting benzodiazepine — direct glucuronidation (no oxidation) makes it the preferred benzodiazepine in elderly and hepatic impairment. Active metabolite of diazepam. Slower onset limits acute-anxiety use; better fit for sustained anxiolysis.',
    routes: ['PO'],
    doses: { 'PO': { min: 10, max: 60, typical: 15, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 286.71,
    refs: [],
  },
  {
    slug: 'flumazenil',
    name: 'Flumazenil',
    aliases: ['Romazicon'],
    category: 'pharmacological',
    mechanism: 'Competitive GABA-A benzodiazepine-site antagonist — reverses benzodiazepine sedation in overdose / procedural over-sedation. Short half-life requires re-dosing after long-acting BZD overdose. Precipitates seizures in chronic BZD users + mixed-overdose with TCAs.',
    routes: ['IV'],
    doses: { 'IV': { min: 0.2, max: 1, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'IV': 0.7 },
    mw_g_mol: 303.29,
    refs: [],
  },
  {
    slug: 'phenobarbital',
    name: 'Phenobarbital',
    aliases: ['Luminal'],
    category: 'pharmacological',
    mechanism: 'Long-acting barbiturate — GABA-A receptor positive allosteric modulator (binds different site than benzodiazepines). Anticonvulsant + sedative. Strong CYP3A4 / CYP2B6 / UGT inducer — major DDI source. Largely replaced by safer antiseizure agents but still used in resource-limited settings + neonatal seizures.',
    routes: ['PO', 'IV', 'IM'],
    doses: { 'PO': { min: 30, max: 300, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 96 },
    mw_g_mol: 232.24,
    refs: [],
  },

  // ── α2 AGONISTS / α1 BLOCKERS / OTHER CARDIO ─────────────────────
  {
    slug: 'clonidine',
    name: 'Clonidine',
    aliases: ['Catapres'],
    category: 'pharmacological',
    mechanism: 'Centrally-acting α2-adrenergic agonist — reduces sympathetic outflow → lower BP + HR. Off-label for ADHD (behavioral hyperactivity), opioid withdrawal symptoms, hot flashes, Tourette tics. Rebound hypertension on abrupt discontinuation.',
    routes: ['PO', 'TD', 'IV'],
    doses: { 'PO': { min: 0.05, max: 0.6, typical: 0.2, unit: 'mg' } },
    half_life_hr: { 'PO': 12 },
    mw_g_mol: 230.10,
    refs: [],
  },
  {
    slug: 'methyldopa',
    name: 'Methyldopa',
    aliases: ['Aldomet'],
    category: 'pharmacological',
    mechanism: 'Centrally-acting α2-adrenergic agonist (active metabolite α-methylnorepinephrine) — reduces sympathetic outflow. Preferred antihypertensive in pregnancy with the longest safety record. Hemolytic anemia + hepatotoxicity at chronic use.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 3000, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 2 },
    mw_g_mol: 211.22,
    refs: [],
  },
  {
    slug: 'doxazosin',
    name: 'Doxazosin',
    aliases: ['Cardura'],
    category: 'pharmacological',
    mechanism: 'Selective α1-adrenergic blocker — relaxes vascular + prostate smooth muscle. Used for hypertension (less first-line since ALLHAT showed worse HF outcomes than thiazides) + symptomatic BPH. First-dose orthostatic hypotension; bedtime dosing recommended.',
    routes: ['PO'],
    doses: { 'PO': { min: 1, max: 16, typical: 4, unit: 'mg' } },
    half_life_hr: { 'PO': 22 },
    mw_g_mol: 451.48,
    refs: [],
  },
  {
    slug: 'terazosin',
    name: 'Terazosin',
    aliases: ['Hytrin'],
    category: 'pharmacological',
    mechanism: 'Selective α1-adrenergic blocker — same vascular + prostate smooth muscle relaxation as doxazosin. Approved for BPH + hypertension. Required to be uptitrated from low doses to avoid first-dose syncope. Off-label research interest as a senolytic-like + lifespan compound (Drosophila + mouse data).',
    routes: ['PO'],
    doses: { 'PO': { min: 1, max: 20, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 12 },
    mw_g_mol: 387.43,
    refs: [],
  },
  {
    slug: 'prazosin',
    name: 'Prazosin',
    aliases: ['Minipress'],
    category: 'pharmacological',
    mechanism: 'Short-acting selective α1-adrenergic blocker. BP lowering + BPH symptom relief. Off-label for PTSD-related nightmares + sleep disturbance (raised α1 tone in PTSD; prazosin softens hyperarousal during sleep).',
    routes: ['PO'],
    doses: { 'PO': { min: 1, max: 20, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 383.40,
    refs: [],
  },
  {
    slug: 'tamsulosin',
    name: 'Tamsulosin',
    aliases: ['Flomax'],
    category: 'pharmacological',
    mechanism: 'α1A-adrenergic-preferring blocker — uroselective (vs vascular) → BPH symptom relief without BP drop. Modified-release once-daily dosing. CYP3A4 + CYP2D6 substrate. "Floppy iris syndrome" complicates cataract surgery.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.4, max: 0.8, typical: 0.4, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 408.51,
    refs: [],
  },
  {
    slug: 'labetalol',
    name: 'Labetalol',
    aliases: ['Trandate'],
    category: 'pharmacological',
    mechanism: 'Combined α1 + non-selective β-adrenergic blocker (~3:1 β:α IV, ~7:1 PO). BP-lowering without reflex tachycardia. Workhorse for hypertension in pregnancy + emergency BP control + pheochromocytoma pre-op management.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 100, max: 1200, typical: 200, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 328.40,
    refs: [],
  },
  {
    slug: 'nimodipine',
    name: 'Nimodipine',
    aliases: ['Nimotop'],
    category: 'pharmacological',
    mechanism: 'Highly lipophilic dihydropyridine CCB — preferential cerebrovascular vasodilation. FDA-approved for prevention of vasospasm-related neurologic deficits after subarachnoid hemorrhage. Hypotension at high doses limits use.',
    routes: ['PO'],
    doses: { 'PO': { min: 60, max: 60, typical: 60, unit: 'mg' } },
    half_life_hr: { 'PO': 9 },
    mw_g_mol: 418.44,
    refs: [],
  },
  {
    slug: 'propafenone',
    name: 'Propafenone',
    aliases: ['Rythmol'],
    category: 'pharmacological',
    mechanism: 'Class IC antiarrhythmic — Na+ channel blocker with weak β-blocker activity. "Pill-in-pocket" cardioversion of paroxysmal AF in structurally normal hearts. CYP2D6 substrate (~7% poor metabolizers have higher levels + more β-blockade). Pro-arrhythmic in ischemic heart disease.',
    routes: ['PO'],
    doses: { 'PO': { min: 150, max: 425, typical: 225, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 341.45,
    refs: [],
  },

  // ── ANTI-SEIZURE EXPANSION ────────────────────────────────────────
  {
    slug: 'levetiracetam',
    name: 'Levetiracetam',
    aliases: ['Keppra'],
    category: 'pharmacological',
    mechanism: 'Pyrrolidone antiseizure — binds synaptic vesicle protein 2A (SV2A) reducing synaptic neurotransmitter release. Broad-spectrum + best-tolerated newer antiseizure agent. Renally cleared, no CYP — DDI-light. Behavioral side effects (irritability, depression) in some patients.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 3000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 7 },
    mw_g_mol: 170.21,
    refs: [],
  },
  {
    slug: 'oxcarbazepine',
    name: 'Oxcarbazepine',
    aliases: ['Trileptal'],
    category: 'pharmacological',
    mechanism: 'Carbamazepine analog — voltage-gated Na+ channel blocker. Active 10-MHD metabolite. Less CYP induction than carbamazepine + no auto-induction → cleaner DDI profile. Hyponatremia in 2.5% (more than carbamazepine).',
    routes: ['PO'],
    doses: { 'PO': { min: 300, max: 2400, typical: 1200, unit: 'mg' } },
    half_life_hr: { 'PO': 9 },
    mw_g_mol: 252.27,
    refs: [],
  },
  {
    slug: 'levetiracetam-er',
    name: 'Levetiracetam (extended-release)',
    aliases: ['Keppra XR'],
    category: 'pharmacological',
    mechanism: 'Extended-release formulation of levetiracetam — same SV2A binding mechanism, once-daily dosing improves adherence. Same pharmacology as IR levetiracetam.',
    routes: ['PO'],
    doses: { 'PO': { min: 500, max: 3000, typical: 1000, unit: 'mg' } },
    half_life_hr: { 'PO': 7 },
    mw_g_mol: 170.21,
    refs: [],
  },

  // ── BISPHOSPHONATES (BONE) ────────────────────────────────────────
  {
    slug: 'alendronate',
    name: 'Alendronate',
    aliases: ['Fosamax'],
    category: 'pharmacological',
    mechanism: 'Aminobisphosphonate — incorporates into hydroxyapatite + inhibits farnesyl pyrophosphate synthase in osteoclasts → osteoclast apoptosis → reduced bone resorption. First-line oral therapy for postmenopausal osteoporosis. Esophageal irritation requires upright positioning + 30 min fast post-dose.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 70, typical: 70, unit: 'mg' } },
    half_life_hr: { 'PO': 240 },
    mw_g_mol: 249.10,
    refs: [],
  },
  {
    slug: 'risedronate',
    name: 'Risedronate',
    aliases: ['Actonel'],
    category: 'pharmacological',
    mechanism: 'Aminobisphosphonate — same osteoclast apoptosis mechanism as alendronate. Less GI irritation; weekly + monthly dosing options. Postmenopausal osteoporosis + glucocorticoid-induced osteoporosis prevention.',
    routes: ['PO'],
    doses: { 'PO': { min: 5, max: 150, typical: 35, unit: 'mg' } },
    half_life_hr: { 'PO': 480 },
    mw_g_mol: 283.11,
    refs: [],
  },
  {
    slug: 'ibandronate',
    name: 'Ibandronate',
    aliases: ['Boniva'],
    category: 'pharmacological',
    mechanism: 'Aminobisphosphonate — once-monthly oral or once-quarterly IV dosing for postmenopausal osteoporosis. Lower vertebral-fracture-only evidence vs alendronate / risedronate (no demonstrated hip-fracture reduction).',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 150, max: 150, typical: 150, unit: 'mg' } },
    half_life_hr: { 'PO': 240 },
    mw_g_mol: 319.23,
    refs: [],
  },
  {
    slug: 'zoledronate',
    name: 'Zoledronate',
    aliases: ['Reclast', 'Zometa'],
    category: 'pharmacological',
    mechanism: 'Most potent IV bisphosphonate — once-yearly infusion for osteoporosis (Reclast) or every 3-4 weeks for malignancy-related bone lesions / hypercalcemia of malignancy (Zometa). Acute-phase reaction + osteonecrosis of jaw + atypical femoral fractures are class concerns at chronic use.',
    routes: ['IV'],
    doses: { 'IV': { min: 4, max: 5, typical: 5, unit: 'mg' } },
    half_life_hr: { 'IV': 167 },
    mw_g_mol: 272.09,
    refs: [],
  },

  // ── OPIOID PARTIAL AGONIST/ANTAGONISTS ────────────────────────────
  {
    slug: 'pentazocine',
    name: 'Pentazocine',
    aliases: ['Talwin'],
    category: 'pharmacological',
    mechanism: 'Mixed κ-opioid agonist + weak μ-opioid antagonist — mid-strength analgesic with ceiling effect on respiratory depression. Dysphoric / hallucinogenic at higher doses (κ-mediated). Schedule IV; less commonly used now.',
    routes: ['PO', 'IV', 'IM', 'SC'],
    doses: { 'PO': { min: 50, max: 100, typical: 50, unit: 'mg' } },
    half_life_hr: { 'PO': 3 },
    mw_g_mol: 285.43,
    refs: [],
  },
  {
    slug: 'nalbuphine',
    name: 'Nalbuphine',
    aliases: ['Nubain'],
    category: 'pharmacological',
    mechanism: 'Mixed κ-opioid agonist + μ-opioid antagonist — same ceiling effect as pentazocine. Used in obstetric analgesia (less neonatal respiratory depression than pure agonists) + procedural pain. Not a controlled substance in the US.',
    routes: ['IV', 'IM', 'SC'],
    doses: { 'IV': { min: 5, max: 20, typical: 10, unit: 'mg' } },
    half_life_hr: { 'IV': 3 },
    mw_g_mol: 357.45,
    refs: [],
  },
  {
    slug: 'butorphanol',
    name: 'Butorphanol',
    aliases: [],
    category: 'pharmacological',
    mechanism: 'Mixed κ-opioid agonist + partial μ agonist — analgesia with ceiling on respiratory depression. Intranasal formulation (Stadol NS) used for migraine + acute pain; abuse potential led to scheduling.',
    routes: ['IV', 'IM', 'IN'],
    doses: { 'IV': { min: 1, max: 4, typical: 2, unit: 'mg' } },
    half_life_hr: { 'IV': 4.5 },
    mw_g_mol: 327.46,
    refs: [],
  },

  // ── ALLERGY / ASTHMA EXPANSION ────────────────────────────────────
  {
    slug: 'cromolyn',
    name: 'Cromolyn',
    aliases: ['Sodium cromoglicate', 'Intal', 'Crolom'],
    category: 'pharmacological',
    mechanism: 'Mast cell stabilizer — inhibits degranulation of pulmonary + ocular + gut mast cells. Inhaled for asthma prophylaxis (not rescue), nasal for allergic rhinitis, ophthalmic for allergic conjunctivitis, oral for systemic mastocytosis.',
    routes: ['INH', 'IN', 'TD', 'PO'],
    doses: { 'INH': { min: 2, max: 8, typical: 4, unit: 'mg' } },
    half_life_hr: { 'INH': 1.5 },
    mw_g_mol: 468.37,
    refs: [],
  },
  {
    slug: 'zafirlukast',
    name: 'Zafirlukast',
    aliases: ['Accolate'],
    category: 'pharmacological',
    mechanism: 'CysLT1 receptor antagonist — same target as montelukast but BID dosing + meaningful CYP2C9 inhibition (raises warfarin INR). Hepatotoxicity warning; less prescribed than montelukast.',
    routes: ['PO'],
    doses: { 'PO': { min: 20, max: 20, typical: 20, unit: 'mg' } },
    half_life_hr: { 'PO': 10 },
    mw_g_mol: 575.68,
    refs: [],
  },
  {
    slug: 'zileuton',
    name: 'Zileuton',
    aliases: ['Zyflo'],
    category: 'pharmacological',
    mechanism: '5-lipoxygenase inhibitor — blocks leukotriene biosynthesis upstream of CysLT1 receptor. Asthma maintenance; less used than montelukast. CYP1A2 inhibitor (raises theophylline + propranolol). Hepatotoxicity warning requires LFT monitoring.',
    routes: ['PO'],
    doses: { 'PO': { min: 600, max: 2400, typical: 1200, unit: 'mg' } },
    half_life_hr: { 'PO': 2.5 },
    mw_g_mol: 236.29,
    refs: [],
  },
  {
    slug: 'beclomethasone',
    name: 'Beclomethasone',
    aliases: ['QVAR', 'Beconase'],
    category: 'pharmacological',
    mechanism: 'Inhaled / intranasal corticosteroid — high topical glucocorticoid potency + extensive first-pass deactivation. Asthma maintenance + allergic rhinitis. One of the older inhaled corticosteroids, broadly affordable.',
    routes: ['INH', 'IN'],
    doses: { 'INH': { min: 0.04, max: 0.32, typical: 0.16, unit: 'mg' } },
    half_life_hr: { 'INH': 3 },
    mw_g_mol: 408.92,
    refs: [],
  },
  {
    slug: 'ciclesonide',
    name: 'Ciclesonide',
    aliases: ['Alvesco'],
    category: 'pharmacological',
    mechanism: 'Inhaled corticosteroid prodrug — activated by lung esterases to des-ciclesonide. Lung-specific activation reduces oropharyngeal candidiasis + dysphonia vs other ICS. Once-daily dosing.',
    routes: ['INH', 'IN'],
    doses: { 'INH': { min: 0.08, max: 0.32, typical: 0.16, unit: 'mg' } },
    half_life_hr: { 'INH': 6 },
    mw_g_mol: 540.69,
    refs: [],
  },
  {
    slug: 'fluticasone-furoate',
    name: 'Fluticasone Furoate',
    aliases: ['Arnuity', 'Flonase Sensimist'],
    category: 'pharmacological',
    mechanism: 'Inhaled / intranasal corticosteroid with the longest receptor binding among ICS class — supports once-daily dosing. Combined with vilanterol (Breo) + with vilanterol + umeclidinium (Trelegy) for asthma + COPD triple-therapy.',
    routes: ['INH', 'IN'],
    doses: { 'INH': { min: 0.1, max: 0.2, typical: 0.1, unit: 'mg' } },
    half_life_hr: { 'INH': 24 },
    mw_g_mol: 538.59,
    refs: [],
  },

  // ── ANTIVIRALS EXPANSION ──────────────────────────────────────────
  {
    slug: 'ganciclovir',
    name: 'Ganciclovir',
    aliases: ['Cytovene'],
    category: 'pharmacological',
    mechanism: 'Acyclic guanosine analog — phosphorylated to triphosphate by viral UL97 (CMV) → competitive substrate + chain-terminator for CMV DNA polymerase. Used for CMV infection in transplant + HIV. IV form; valganciclovir is the oral prodrug.',
    routes: ['IV', 'TD'],
    doses: { 'IV': { min: 5, max: 10, typical: 5, unit: 'mg' } },
    half_life_hr: { 'IV': 4 },
    mw_g_mol: 255.23,
    refs: [],
  },
  {
    slug: 'valganciclovir',
    name: 'Valganciclovir',
    aliases: ['Valcyte'],
    category: 'pharmacological',
    mechanism: 'L-valyl ester prodrug of ganciclovir — first-pass valine hydrolysis improves oral F to ~60%. Same anti-CMV mechanism. Standard outpatient CMV prophylaxis post-transplant.',
    routes: ['PO'],
    doses: { 'PO': { min: 450, max: 900, typical: 900, unit: 'mg' } },
    half_life_hr: { 'PO': 4 },
    mw_g_mol: 354.36,
    refs: [],
  },
  {
    slug: 'famciclovir',
    name: 'Famciclovir',
    aliases: ['Famvir'],
    category: 'pharmacological',
    mechanism: 'Diacetyl-6-deoxy-penciclovir prodrug — converted to penciclovir, which is phosphorylated by viral thymidine kinase (HSV / VZV) to triphosphate competitive-substrate / chain-terminator. Same indications as valacyclovir; alternative when patient tolerance differs.',
    routes: ['PO'],
    doses: { 'PO': { min: 125, max: 1500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 2.5 },
    mw_g_mol: 321.34,
    refs: [],
  },
  {
    slug: 'entecavir',
    name: 'Entecavir',
    aliases: ['Baraclude'],
    category: 'pharmacological',
    mechanism: 'Guanosine nucleoside analog — selective HBV polymerase inhibitor. First-line oral therapy for chronic HBV with high barrier to resistance + minimal HIV cross-activity. Renal excretion; food reduces F.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.5, max: 1, typical: 0.5, unit: 'mg' } },
    half_life_hr: { 'PO': 130 },
    mw_g_mol: 277.28,
    refs: [],
  },
  {
    slug: 'baloxavir',
    name: 'Baloxavir Marboxil',
    aliases: ['Xofluza'],
    category: 'pharmacological',
    mechanism: 'Influenza cap-dependent endonuclease (PA subunit) inhibitor — blocks viral mRNA synthesis. Single-dose oral therapy advantage over oseltamivir (5-day course). Reduced influenza A activity in some 2021 strains via PA I38T resistance mutation.',
    routes: ['PO'],
    doses: { 'PO': { min: 40, max: 80, typical: 40, unit: 'mg' } },
    half_life_hr: { 'PO': 80 },
    mw_g_mol: 571.55,
    refs: [],
  },

  // ── ANTIBIOTICS EXPANSION ─────────────────────────────────────────
  {
    slug: 'linezolid',
    name: 'Linezolid',
    aliases: ['Zyvox'],
    category: 'pharmacological',
    mechanism: 'Oxazolidinone — binds 23S rRNA of bacterial 50S subunit blocking 70S initiation complex formation. Active against MRSA + VRE. Reversible MAO inhibition → serotonin syndrome risk with SSRIs. Bone marrow suppression at courses > 14 days.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 600, max: 600, typical: 600, unit: 'mg' } },
    half_life_hr: { 'PO': 5 },
    mw_g_mol: 337.35,
    refs: [],
  },
  {
    slug: 'cefuroxime',
    name: 'Cefuroxime',
    aliases: ['Ceftin', 'Zinacef'],
    category: 'pharmacological',
    mechanism: 'Second-generation cephalosporin β-lactam — better gram-negative + β-lactamase stability than first-generation. Oral axetil prodrug + IV form. Common for acute otitis media + bronchitis + Lyme disease (early).',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 250, max: 500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'PO': 1.5 },
    mw_g_mol: 424.39,
    refs: [],
  },
  {
    slug: 'cefdinir',
    name: 'Cefdinir',
    aliases: ['Omnicef'],
    category: 'pharmacological',
    mechanism: 'Third-generation oral cephalosporin — extended gram-negative coverage; common for AOM + sinusitis + skin/soft tissue. Iron co-administration causes a non-pathological reddish stool (cefdinir-iron complex) — alarming but harmless.',
    routes: ['PO'],
    doses: { 'PO': { min: 300, max: 600, typical: 300, unit: 'mg' } },
    half_life_hr: { 'PO': 1.7 },
    mw_g_mol: 395.42,
    refs: [],
  },
  {
    slug: 'sulfasalazine',
    name: 'Sulfasalazine',
    aliases: ['Azulfidine'],
    category: 'pharmacological',
    mechanism: 'Sulfonamide-mesalamine prodrug — gut bacteria cleave the azo bond releasing 5-ASA (anti-inflammatory, mesalamine-active component) + sulfapyridine (mostly side-effect-driver). Used for IBD + rheumatoid arthritis (DMARD).',
    routes: ['PO'],
    doses: { 'PO': { min: 500, max: 4000, typical: 2000, unit: 'mg' } },
    half_life_hr: { 'PO': 6 },
    mw_g_mol: 398.39,
    refs: [],
  },

  // ── GI MOTILITY / SECRETION ───────────────────────────────────────
  {
    slug: 'linaclotide',
    name: 'Linaclotide',
    aliases: ['Linzess'],
    category: 'pharmacological',
    mechanism: 'GC-C (guanylate cyclase-C) agonist — raises intestinal cGMP → CFTR-mediated chloride / bicarbonate / water secretion into lumen. Approved for chronic idiopathic constipation + IBS-C. Minimal systemic absorption → DDI-light. Diarrhea is the main dose-limiting side effect.',
    routes: ['PO'],
    doses: { 'PO': { min: 0.072, max: 0.290, typical: 0.145, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 1526.74,
    refs: [],
  },
  {
    slug: 'lubiprostone',
    name: 'Lubiprostone',
    aliases: ['Amitiza'],
    category: 'pharmacological',
    mechanism: 'Selective ClC-2 chloride-channel activator on intestinal epithelium → enhanced fluid secretion. Used for chronic idiopathic constipation + opioid-induced constipation. Nausea is the most common dose-limiting effect (taken with food helps).',
    routes: ['PO'],
    doses: { 'PO': { min: 0.008, max: 0.024, typical: 0.024, unit: 'mg' } },
    half_life_hr: { 'PO': 1 },
    mw_g_mol: 390.46,
    refs: [],
  },
  {
    slug: 'diphenoxylate-atropine',
    name: 'Diphenoxylate / Atropine',
    aliases: ['Lomotil'],
    category: 'pharmacological',
    mechanism: 'Diphenoxylate (μ-opioid agonist with limited CNS access at therapeutic doses) + atropine (anticholinergic — added to deter abuse). Used for symptomatic diarrhea. Schedule V due to abuse-potential precedent; loperamide largely supplanted it.',
    routes: ['PO'],
    doses: { 'PO': { min: 2.5, max: 20, typical: 5, unit: 'mg' } },
    half_life_hr: { 'PO': 12 },
    refs: [],
  },

  // ── DERM / TOPICAL EXPANSION ──────────────────────────────────────
  {
    slug: 'hydroquinone',
    name: 'Hydroquinone',
    aliases: [],
    category: 'topical',
    mechanism: 'Tyrosinase inhibitor — blocks melanin synthesis in melanocytes. Topical 2% (OTC in some countries) and 4% (Rx) for melasma + post-inflammatory hyperpigmentation. Long-term high-strength use risks ochronosis (paradoxical darkening) — typically cycled.',
    routes: ['TD'],
    doses: { 'TD': { min: 2, max: 4, typical: 4, unit: 'mg' } },
    half_life_hr: { 'TD': 24 },
    mw_g_mol: 110.11,
    refs: [],
  },
  {
    slug: 'calcipotriene',
    name: 'Calcipotriene',
    aliases: ['Calcipotriol', 'Dovonex'],
    category: 'topical',
    mechanism: 'Topical vitamin D3 analog — VDR agonist on keratinocytes that normalizes hyperproliferation in psoriasis. Often combined with topical corticosteroid (calcipotriene + betamethasone, Taclonex) for synergistic plaque reduction.',
    routes: ['TD'],
    doses: { 'TD': { min: 0.05, max: 0.5, typical: 0.05, unit: 'mg' } },
    half_life_hr: { 'TD': 14 },
    mw_g_mol: 412.62,
    refs: [],
  },
  {
    slug: 'crisaborole',
    name: 'Crisaborole',
    aliases: ['Eucrisa'],
    category: 'topical',
    mechanism: 'Topical PDE4 inhibitor — raises keratinocyte cAMP → reduced inflammatory cytokine release. Approved for atopic dermatitis as steroid-sparing alternative. Application-site burning (~5%) is the most common adverse effect.',
    routes: ['TD'],
    doses: { 'TD': { min: 20, max: 60, typical: 40, unit: 'mg' } },
    half_life_hr: { 'TD': 14 },
    mw_g_mol: 251.05,
    refs: [],
  },
  {
    slug: 'fulvestrant',
    name: 'Fulvestrant',
    aliases: ['Faslodex'],
    category: 'hormone',
    mechanism: 'Pure estrogen receptor antagonist + degrader — binds ER, blocks dimerization and DNA binding, marks ER for proteasomal degradation. IM depot for advanced ER-positive breast cancer. No agonist activity (unlike tamoxifen) → no endometrial-cancer risk.',
    routes: ['IM'],
    doses: { 'IM': { min: 250, max: 500, typical: 500, unit: 'mg' } },
    half_life_hr: { 'IM': 1200 },
    mw_g_mol: 606.77,
    refs: [],
  },

  // ── MISC ATTAINABLE ───────────────────────────────────────────────
  {
    slug: 'acetazolamide',
    name: 'Acetazolamide',
    aliases: ['Diamox'],
    category: 'pharmacological',
    mechanism: 'Carbonic anhydrase inhibitor — blocks proximal tubule HCO3- reabsorption + reduces aqueous humor production + reduces CSF production. Used for glaucoma, altitude sickness prophylaxis, idiopathic intracranial hypertension. Metabolic acidosis + paresthesias common.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 125, max: 1000, typical: 250, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 222.24,
    refs: [],
  },
  {
    slug: 'pyridostigmine',
    name: 'Pyridostigmine',
    aliases: ['Mestinon'],
    category: 'pharmacological',
    mechanism: 'Reversible peripheral acetylcholinesterase inhibitor — quaternary ammonium prevents BBB penetration → no CNS effects. First-line symptomatic therapy for myasthenia gravis. Cholinergic crisis at overdose; nicotine-receptor desensitization under-treats severe cases.',
    routes: ['PO', 'IV'],
    doses: { 'PO': { min: 30, max: 600, typical: 60, unit: 'mg' } },
    half_life_hr: { 'PO': 3.5 },
    mw_g_mol: 261.10,
    refs: [],
  },
  {
    slug: 'sumatriptan-succinate',
    name: 'Sumatriptan Succinate (specifically)',
    aliases: ['Imitrex Succinate'],
    category: 'pharmacological',
    mechanism: 'Sumatriptan as the succinate salt — sublingual + injectable formulations use this salt for solubility. Same 5-HT1B/1D agonism + cranial vasoconstriction as sumatriptan. Listed separately because the salt MW differs from free base for solubility-dependent dosing.',
    routes: ['SC', 'IN'],
    doses: { 'SC': { min: 4, max: 6, typical: 6, unit: 'mg' } },
    half_life_hr: { 'SC': 2 },
    mw_g_mol: 413.49,
    refs: [],
  },
  {
    slug: 'orphenadrine',
    name: 'Orphenadrine',
    aliases: ['Norflex'],
    category: 'pharmacological',
    mechanism: 'Anticholinergic + NMDA antagonist + weak NET inhibitor — centrally-acting muscle relaxant for acute musculoskeletal pain. Anticholinergic burden similar to cyclobenzaprine; Beers-list problematic.',
    routes: ['PO', 'IV', 'IM'],
    doses: { 'PO': { min: 100, max: 200, typical: 100, unit: 'mg' } },
    half_life_hr: { 'PO': 14 },
    mw_g_mol: 269.39,
    refs: [],
  },
  {
    slug: 'carisoprodol',
    name: 'Carisoprodol',
    aliases: ['Soma'],
    category: 'pharmacological',
    mechanism: 'Skeletal muscle relaxant — pro-drug largely converted to meprobamate (a Schedule IV barbiturate-like sedative). Schedule IV; abuse potential + physical dependence are concerns. Outpatient acute musculoskeletal pain only short-term.',
    routes: ['PO'],
    doses: { 'PO': { min: 250, max: 350, typical: 250, unit: 'mg' } },
    half_life_hr: { 'PO': 8 },
    mw_g_mol: 260.33,
    refs: [],
  },
];

function main(): void {
  const data = JSON.parse(readFileSync(COMPOUNDS_PATH, 'utf-8')) as Array<Record<string, unknown>>;
  const bySlug = new Map(data.map(c => [c['slug'] as string, c]));

  let added = 0;
  let skipped = 0;
  for (const stub of STUBS) {
    if (bySlug.has(stub.slug)) {
      skipped++;
      continue;
    }
    data.push(stub as unknown as Record<string, unknown>);
    bySlug.set(stub.slug, stub as unknown as Record<string, unknown>);
    added++;
  }

  writeFileSync(COMPOUNDS_PATH, JSON.stringify(data, null, 2) + '\n');

  console.log('\nWave 0b sub-batch 9 — benzos / cardio / bone / abx tail:');
  console.log(`  Added: ${added}`);
  console.log(`  Skipped (already present): ${skipped}`);
  console.log(`  Catalog: ${data.length} compounds`);
}

main();
